/* ============================================================
   A&M QUIZZ — BANQUE DE QUESTIONS
   ------------------------------------------------------------
   Chaque question a la forme :
   { category, type, prompt, image (optionnel), reference (optionnel) }

   - "reference" = la réponse attendue, affichée à l'hôte ET à tous
     les joueurs pendant la phase de correction (sauf pour le petit
     bac, où "reference" contient juste des EXEMPLES pour aider
     l'hôte à juger, pas LA réponse).
   - L'hôte valide chaque réponse joueur par Vrai/Faux, quelle que
     soit la catégorie : c'est un choix demandé explicitement (jeu
     entre amis, pas de correction automatique rigide).

   POUR AJOUTER DES QUESTIONS : copie une ligne existante de la
   catégorie voulue et remplace le contenu. Aucune limite de taille.
   ============================================================ */

/* NOTE (fix) : quand "Petit Bac" est sélectionné seul (sans autre catégorie),
   on peut piocher jusqu'au nombre de questions demandé (et non plafonné à 3),
   sinon il reste un "round" limité mélangé aux autres catégories. Voir app.js. */
const QUESTION_BANK = {

  /* ================= ANIMAUX (à deviner) ================= */
  // Affichées via un gros emoji (fiable, pas de lien image cassé).
  // Remplace "image" par une vraie URL de photo si tu veux.
  animaux: [
    { prompt: "Quel est cet animal ?", image: "🦒", reference: "Girafe" },
    { prompt: "Quel est cet animal ?", image: "🦁", reference: "Lion" },
    { prompt: "Quel est cet animal ?", image: "🐘", reference: "Éléphant" },
    { prompt: "Quel est cet animal ?", image: "🦓", reference: "Zèbre" },
    { prompt: "Quel est cet animal ?", image: "🦛", reference: "Hippopotame" },
    { prompt: "Quel est cet animal ?", image: "🐊", reference: "Crocodile" },
    { prompt: "Quel est cet animal ?", image: "🦉", reference: "Hibou" },
    { prompt: "Quel est cet animal ?", image: "🦅", reference: "Aigle" },
    { prompt: "Quel est cet animal ?", image: "🦇", reference: "Chauve-souris" },
    { prompt: "Quel est cet animal ?", image: "🐬", reference: "Dauphin" },
    { prompt: "Quel est cet animal ?", image: "🐋", reference: "Baleine" },
    { prompt: "Quel est cet animal ?", image: "🦈", reference: "Requin" },
    { prompt: "Quel est cet animal ?", image: "🐢", reference: "Tortue" },
    { prompt: "Quel est cet animal ?", image: "🦔", reference: "Hérisson" },
    { prompt: "Quel est cet animal ?", image: "🦦", reference: "Loutre" },
    { prompt: "Quel est cet animal ?", image: "🦥", reference: "Paresseux" },
    { prompt: "Quel est cet animal ?", image: "🦘", reference: "Kangourou" },
    { prompt: "Quel est cet animal ?", image: "🐨", reference: "Koala" },
    { prompt: "Quel est cet animal ?", image: "🐼", reference: "Panda" },
    { prompt: "Quel est cet animal ?", image: "🦙", reference: "Lama" },
    { prompt: "Quel est cet animal ?", image: "🦌", reference: "Cerf" },
    { prompt: "Quel est cet animal ?", image: "🐗", reference: "Sanglier" },
    { prompt: "Quel est cet animal ?", image: "🦡", reference: "Blaireau" },
    { prompt: "Quel est cet animal ?", image: "🦫", reference: "Castor" },
    { prompt: "Quel est cet animal ?", image: "🦩", reference: "Flamant rose" },
    { prompt: "Quel est cet animal ?", image: "🦚", reference: "Paon" },
    { prompt: "Quel est cet animal ?", image: "🦜", reference: "Perroquet" },
    { prompt: "Quel est cet animal ?", image: "🐧", reference: "Manchot" },
    { prompt: "Quel est cet animal ?", image: "🦭", reference: "Phoque" },
    { prompt: "Quel est cet animal ?", image: "🐌", reference: "Escargot" },
    { prompt: "Quel est cet animal ?", image: "🦋", reference: "Papillon" },
    { prompt: "Quel est cet animal ?", image: "🐝", reference: "Abeille" },
    { prompt: "Quel est cet animal ?", image: "🕷️", reference: "Araignée" },
    { prompt: "Quel est cet animal ?", image: "🦂", reference: "Scorpion" },
    { prompt: "Quel est cet animal ?", image: "🐙", reference: "Poulpe" },
    { prompt: "Quel est cet animal ?", image: "🦑", reference: "Calmar" },
    { prompt: "Quel est cet animal ?", image: "🦞", reference: "Homard" },
    { prompt: "Quel est cet animal ?", image: "🦀", reference: "Crabe" },
    { prompt: "Quel est cet animal ?", image: "🐫", reference: "Chameau" },
    { prompt: "Quel est cet animal ?", image: "🦃", reference: "Dinde" },
    { prompt: "Quel est cet animal ?", image: "🐿️", reference: "Écureuil" },
    { prompt: "Quel animal est surnommé le « roi de la jungle » ?", reference: "Le lion" },
    { prompt: "Quel est le plus grand animal terrestre actuel ?", reference: "L'éléphant d'Afrique" },
    { prompt: "Quel est le plus grand animal du monde (marin ou terrestre) ?", reference: "La baleine bleue" },
    { prompt: "Quel oiseau ne sait pas voler mais court très vite en Afrique ?", reference: "L'autruche" },
    { prompt: "Quel animal change de couleur pour se camoufler ?", reference: "Le caméléon" },
  ],

  /* ================= PETIT BAC ================= */
  // Pas de "bonne réponse" unique : "reference" = exemples pour l'hôte.
  // Catégories du round personnalisables. 8 minimum demandés, 15 fournis.
  petit_bac: [
    { letter: "G", categories: ["Animal", "Célébrité", "Pays", "Prénom", "Métier", "Objet"],
      reference: { Animal: "Girafe", Célébrité: "Gyökeres", Pays: "Grèce", Prénom: "Gabriel", Métier: "Garagiste", Objet: "Gant" } },
    { letter: "M", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Marque"],
      reference: { Animal: "Mouton", Célébrité: "Messi", Ville: "Marseille", Prénom: "Marie", "Fruit/Légume": "Mangue", Marque: "Michelin" } },
    { letter: "P", categories: ["Animal", "Pays", "Prénom", "Métier", "Objet", "Sport"],
      reference: { Animal: "Panda", Pays: "Portugal", Prénom: "Paul", Métier: "Pompier", Objet: "Parapluie", Sport: "Pétanque" } },
    { letter: "C", categories: ["Animal", "Célébrité", "Ville", "Fruit/Légume", "Marque", "Métier"],
      reference: { Animal: "Chat", Célébrité: "Cristiano Ronaldo", Ville: "Cannes", "Fruit/Légume": "Citron", Marque: "Chanel", Métier: "Chirurgien" } },
    { letter: "L", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Lion", Pays: "Luxembourg", Prénom: "Léa", Objet: "Lampe", Sport: "Lutte", Marque: "Lacoste" } },
    { letter: "B", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Baleine", Célébrité: "Beyoncé", Ville: "Bordeaux", Prénom: "Benjamin", "Fruit/Légume": "Banane", Métier: "Boulanger" } },
    { letter: "R", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Renard", Pays: "Roumanie", Prénom: "Robert", Objet: "Radio", Sport: "Rugby", Marque: "Renault" } },
    { letter: "T", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Tigre", Célébrité: "Taylor Swift", Ville: "Toulouse", Prénom: "Thomas", "Fruit/Légume": "Tomate", Métier: "Traducteur" } },
    { letter: "S", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Serpent", Pays: "Suède", Prénom: "Sarah", Objet: "Stylo", Sport: "Ski", Marque: "Samsung" } },
    { letter: "A", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Aigle", Célébrité: "Adele", Ville: "Amiens", Prénom: "Alice", "Fruit/Légume": "Ananas", Métier: "Avocat" } },
    { letter: "D", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Dauphin", Pays: "Danemark", Prénom: "David", Objet: "Drapeau", Sport: "Danse", Marque: "Danone" } },
    { letter: "V", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Vache", Célébrité: "Vincent Cassel", Ville: "Valence", Prénom: "Victor", "Fruit/Légume": "Vigne (raisin)", Métier: "Vétérinaire" } },
    { letter: "N", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Nandou", Pays: "Norvège", Prénom: "Nicolas", Objet: "Nappe", Sport: "Natation", Marque: "Nike" } },
    { letter: "H", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Hibou", Célébrité: "Hugh Jackman", Ville: "Honfleur", Prénom: "Hugo", "Fruit/Légume": "Haricot", Métier: "Horloger" } },
    { letter: "E", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Écureuil", Pays: "Espagne", Prénom: "Emma", Objet: "Écharpe", Sport: "Escrime", Marque: "Evian" } },
  ],

  /* ================= REBUS ================= */
  rebus: [
    { prompt: "2 + 🖐 (main)", reference: "Demain" },
    { prompt: "1 + VERS", reference: "Univers" },
    { prompt: "CHÂ + TEAU", reference: "Château" },
    { prompt: "SOU + RIZ", reference: "Souris" },
    { prompt: "TA + PIS", reference: "Tapis" },
    { prompt: "CHA + PEAU", reference: "Chapeau" },
    { prompt: "POU + BELLE", reference: "Poubelle" },
    { prompt: "BU + REAU", reference: "Bureau" },
    { prompt: "GUI + TARE", reference: "Guitare" },
    { prompt: "MAR + TEAU", reference: "Marteau" },
    { prompt: "PA + PILLON", reference: "Papillon" },
    { prompt: "CO + QUILLE", reference: "Coquille" },
    { prompt: "SA + LADE", reference: "Salade" },
    { prompt: "CRA + VATE", reference: "Cravate" },
    { prompt: "AN + ANAS", reference: "Ananas" },
    { prompt: "CHE + VAL", reference: "Cheval" },
    { prompt: "COR + BEAU", reference: "Corbeau" },
    { prompt: "PAN + THÈRE", reference: "Panthère" },
    { prompt: "GRE + NOUILLE", reference: "Grenouille" },
    { prompt: "É + TOILE", reference: "Étoile" },
    { prompt: "SA + PIN", reference: "Sapin" },
    { prompt: "CHAM + PIGNON", reference: "Champignon" },
    { prompt: "PARA + SOL", reference: "Parasol" },
    { prompt: "VIO + LON", reference: "Violon" },
    { prompt: "PI + ANO", reference: "Piano" },
    { prompt: "EAU (son O) + REILLE", reference: "Oreille" },
    { prompt: "LAN + TERNE", reference: "Lanterne" },
    { prompt: "MON + TAGNE", reference: "Montagne" },
    { prompt: "BA + LAI", reference: "Balai" },
    { prompt: "NI + VEAU", reference: "Niveau" },
    { prompt: "CHA + MEAU", reference: "Chameau" },
    { prompt: "RE + NARD", reference: "Renard" },
    { prompt: "HI + VER", reference: "Hiver" },
    { prompt: "PRIN + TEMPS", reference: "Printemps" },
    { prompt: "MON + NAIE", reference: "Monnaie" },
    { prompt: "PAS + TÈQUE", reference: "Pastèque" },
  ],

  /* ================= HISTOIRE ================= */
  histoire: [
    { prompt: "En quelle année a eu lieu la prise de la Bastille ?", reference: "1789" },
    { prompt: "Quel empereur romain a légalisé le christianisme ?", reference: "Constantin" },
    { prompt: "Qui était le premier empereur des Français ?", reference: "Napoléon Bonaparte" },
    { prompt: "En quelle année a débuté la Première Guerre mondiale ?", reference: "1914" },
    { prompt: "Quel traité a mis fin à la Première Guerre mondiale ?", reference: "Le traité de Versailles" },
    { prompt: "Quelle civilisation a construit les pyramides de Gizeh ?", reference: "Les Égyptiens" },
    { prompt: "Qui a lancé l'appel du 18 juin 1940 ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année le mur de Berlin est-il tombé ?", reference: "1989" },
    { prompt: "Quel roi de France est surnommé le « Roi Soleil » ?", reference: "Louis XIV" },
    { prompt: "Quelle bataille marque la défaite finale de Napoléon en 1815 ?", reference: "Waterloo" },
    { prompt: "Qui a dirigé l'URSS pendant la majeure partie de la Seconde Guerre mondiale ?", reference: "Staline" },
    { prompt: "Quelle bataille de 1916 est un symbole de l'enfer des tranchées ?", reference: "Verdun" },
    { prompt: "Quel événement déclenche directement la Première Guerre mondiale ?", reference: "L'assassinat de l'archiduc François-Ferdinand" },
    { prompt: "En quelle année Hitler prend-il le pouvoir en Allemagne ?", reference: "1933" },
    { prompt: "Quelle opération du 6 juin 1944 marque le début de la libération de la France ?", reference: "Le débarquement de Normandie (Overlord)" },
    { prompt: "Qui était le chef de l'État français de Vichy ?", reference: "Philippe Pétain" },
    { prompt: "En quelle année la Seconde Guerre mondiale se termine-t-elle ?", reference: "1945" },
    { prompt: "Quel roi de France a été guillotiné en 1793 ?", reference: "Louis XVI" },
    { prompt: "Quelle est la date symbolique du début de la Révolution française ?", reference: "14 juillet 1789" },
    { prompt: "Quel pays envahit la Pologne en septembre 1939 ?", reference: "L'Allemagne nazie" },
    { prompt: "Quel accord de 1938 cède les Sudètes à Hitler ?", reference: "Les accords de Munich" },
    { prompt: "Quelle organisation est créée en 1945 pour maintenir la paix mondiale ?", reference: "L'ONU" },
    { prompt: "Quel événement de 1917 fait sortir la Russie de la guerre ?", reference: "La révolution russe" },
    { prompt: "Qui a été le premier président de la Ve République ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année Christophe Colomb atteint-il l'Amérique ?", reference: "1492" },
    { prompt: "Quel empire romain tombe en 476 ?", reference: "L'Empire romain d'Occident" },
    { prompt: "Quelle reine d'Égypte est célèbre pour sa liaison avec César puis Marc Antoine ?", reference: "Cléopâtre" },
    { prompt: "Quel mur sépare Berlin-Est et Berlin-Ouest de 1961 à 1989 ?", reference: "Le mur de Berlin" },
    { prompt: "Quelle guerre oppose le Nord et le Sud des États-Unis (1861-1865) ?", reference: "La guerre de Sécession" },
    { prompt: "Quel navire britannique coule en 1912 après avoir heurté un iceberg ?", reference: "Le Titanic" },
    { prompt: "Quel pharaon égyptien est célèbre pour son masque funéraire en or ?", reference: "Toutankhamon" },
    { prompt: "Quelle bataille de 1815 se déroule en Belgique actuelle ?", reference: "Waterloo" },
    { prompt: "Quel roi anglais signe la Magna Carta en 1215 ?", reference: "Jean sans Terre" },
    { prompt: "Quelle épidémie décime l'Europe au XIVe siècle ?", reference: "La peste noire" },
    { prompt: "Quel explorateur portugais réalise le premier tour du monde (expédition achevée après sa mort) ?", reference: "Magellan" },
    { prompt: "En quelle année la France abolit-elle l'esclavage pour la seconde fois (définitivement) ?", reference: "1848" },
    { prompt: "Quel événement déclenche la Terreur en France en 1793 ?", reference: "L'exécution du roi et la guerre contre les monarchies européennes" },
    { prompt: "Quel traité de 1648 met fin à la guerre de Trente Ans ?", reference: "La paix de Westphalie" },
    { prompt: "Quelle civilisation antique a inventé la démocratie ?", reference: "Les Grecs (Athènes)" },
    { prompt: "Quel dirigeant chinois fonde la République populaire de Chine en 1949 ?", reference: "Mao Zedong" },
  ],

  /* ================= GRANDES FIGURES & ÉVÉNEMENTS ================= */
  grandes_figures: [
    { prompt: "Je suis un général corse devenu empereur des Français. Qui suis-je ?", reference: "Napoléon Bonaparte" },
    { prompt: "Je suis une jeune paysanne qui a mené l'armée française à Orléans avant d'être brûlée vive. Qui suis-je ?", reference: "Jeanne d'Arc" },
    { prompt: "Je suis un physicien qui a formulé la théorie de la relativité. Qui suis-je ?", reference: "Albert Einstein" },
    { prompt: "Je suis un pasteur américain qui a prononcé le discours « I have a dream ». Qui suis-je ?", reference: "Martin Luther King" },
    { prompt: "Je suis une reine d'Égypte, dernière souveraine de la dynastie ptolémaïque. Qui suis-je ?", reference: "Cléopâtre" },
    { prompt: "Je suis un général qui a lancé l'appel du 18 juin 1940 depuis Londres. Qui suis-je ?", reference: "Charles de Gaulle" },
    { prompt: "Je suis un chef d'État sud-africain emprisonné 27 ans avant de devenir président. Qui suis-je ?", reference: "Nelson Mandela" },
    { prompt: "Je suis une scientifique polonaise, seule personne à avoir reçu deux prix Nobel dans deux domaines différents. Qui suis-je ?", reference: "Marie Curie" },
    { prompt: "Je suis un roi de France qui a régné plus de 70 ans, le plus long règne de l'histoire de France. Qui suis-je ?", reference: "Louis XIV" },
    { prompt: "Je suis un dictateur allemand responsable de la Seconde Guerre mondiale et de la Shoah. Qui suis-je ?", reference: "Adolf Hitler" },
    { prompt: "Je suis un premier ministre britannique qui a résisté aux nazis pendant la bataille d'Angleterre. Qui suis-je ?", reference: "Winston Churchill" },
    { prompt: "Je suis un empereur romain qui a légalisé le christianisme. Qui suis-je ?", reference: "Constantin" },
    { prompt: "Je suis un navigateur qui a atteint l'Amérique en 1492 en cherchant une route vers les Indes. Qui suis-je ?", reference: "Christophe Colomb" },
    { prompt: "Je suis une résistante et ministre française, rescapée des camps, dont le visage est sur les manuels d'histoire. Qui suis-je ?", reference: "Simone Veil" },
    { prompt: "Je suis un philosophe grec, maître de Platon devenu maître d'Aristote lui-même. Qui suis-je ?", reference: "Socrate" },
    { prompt: "Je suis un empereur français vaincu définitivement à Waterloo en 1815. Qui suis-je ?", reference: "Napoléon Bonaparte" },
    { prompt: "Je suis un leader indien qui a mené la résistance non-violente contre la colonisation britannique. Qui suis-je ?", reference: "Gandhi" },
    { prompt: "Je suis un tsar russe qui a modernisé la Russie et fondé Saint-Pétersbourg. Qui suis-je ?", reference: "Pierre le Grand" },
    { prompt: "Je suis une figure de la Résistance française, chargé par de Gaulle d'unifier les mouvements clandestins. Qui suis-je ?", reference: "Jean Moulin" },
    { prompt: "Je suis un roi macédonien qui a conquis un immense empire jusqu'en Inde avant 33 ans. Qui suis-je ?", reference: "Alexandre le Grand" },
    { prompt: "Je suis un président américain assassiné à Dallas en 1963. Qui suis-je ?", reference: "John F. Kennedy" },
    { prompt: "Je suis un empereur romain connu pour avoir conquis la Gaule. Qui suis-je ?", reference: "Jules César" },
    { prompt: "Je suis un inventeur américain à qui l'on attribue l'ampoule électrique. Qui suis-je ?", reference: "Thomas Edison" },
    { prompt: "Je suis une reine de France, épouse de Louis XVI, guillotinée en 1793. Qui suis-je ?", reference: "Marie-Antoinette" },
    { prompt: "Je suis un peintre néerlandais connu pour m'être coupé l'oreille. Qui suis-je ?", reference: "Vincent van Gogh" },
    { prompt: "Je suis le premier homme à avoir marché sur la Lune, en 1969. Qui suis-je ?", reference: "Neil Armstrong" },
    { prompt: "Je suis un chef militaire carthaginois qui a traversé les Alpes avec des éléphants. Qui suis-je ?", reference: "Hannibal Barca" },
    { prompt: "Je suis un compositeur allemand devenu sourd qui a continué à composer. Qui suis-je ?", reference: "Ludwig van Beethoven" },
    { prompt: "Je suis un moine allemand à l'origine de la Réforme protestante. Qui suis-je ?", reference: "Martin Luther" },
    { prompt: "Je suis un pharaon dont la tombe intacte a été découverte en 1922 par Howard Carter. Qui suis-je ?", reference: "Toutankhamon" },
    { prompt: "Je suis une aviatrice américaine disparue en 1937 en tentant de faire le tour du monde. Qui suis-je ?", reference: "Amelia Earhart" },
    { prompt: "Je suis un écrivain et aviateur français, auteur du « Petit Prince », disparu en vol en 1944. Qui suis-je ?", reference: "Antoine de Saint-Exupéry" },
    { prompt: "Je suis un chef d'État soviétique à l'origine de la Révolution d'Octobre 1917. Qui suis-je ?", reference: "Lénine" },
    { prompt: "Je suis un savant italien condamné par l'Église pour avoir défendu que la Terre tourne autour du Soleil. Qui suis-je ?", reference: "Galilée" },
  ],

  /* ================= FRANÇAIS ================= */
  francais: [
    { prompt: "Quel est le féminin de « loup » ?", reference: "Louve" },
    { prompt: "Conjuguez « aller » à la 1ère personne du singulier au futur simple.", reference: "J'irai" },
    { prompt: "Quel est le pluriel de « cheval » ?", reference: "Chevaux" },
    { prompt: "Comment appelle-t-on une figure de style qui compare deux éléments avec « comme » ?", reference: "Une comparaison" },
    { prompt: "Quel est l'antonyme de « heureux » ?", reference: "Malheureux (ou triste)" },
    { prompt: "Combien de « p » y a-t-il dans le mot « appartement » ?", reference: "Deux" },
    { prompt: "Quel est le participe passé du verbe « prendre » ?", reference: "Pris" },
    { prompt: "Comment appelle-t-on une phrase qui pose une question ?", reference: "Une phrase interrogative" },
    { prompt: "Quel est le contraire de « monter » ?", reference: "Descendre" },
    { prompt: "« Cet homme est plus grand que moi » : quel est le mot qui exprime la comparaison ?", reference: "Plus... que" },
    { prompt: "Quel est le féminin de « acteur » ?", reference: "Actrice" },
    { prompt: "Comment écrit-on correctement : « malgré que » ou « bien que » est correct grammaticalement ?", reference: "Bien que" },
    { prompt: "Quel est l'homophone de « ver » qui désigne la couleur ?", reference: "Vert" },
    { prompt: "Quel temps exprime une action habituelle dans le passé : « Il jouait tous les jours » ?", reference: "L'imparfait" },
    { prompt: "Quel est le synonyme de « rapide » ?", reference: "Vite (ou véloce)" },
    { prompt: "Comment appelle-t-on un mot qui a le même sens qu'un autre ?", reference: "Un synonyme" },
    { prompt: "Quel est le pluriel de « journal » ?", reference: "Journaux" },
    { prompt: "« Je mange » à quelle personne et quel temps ?", reference: "1ère personne du singulier, présent" },
    { prompt: "Quel est l'antonyme de « facile » ?", reference: "Difficile" },
    { prompt: "Comment appelle-t-on la répétition d'un son en début de mots proches (« Pour qui sont ces serpents qui sifflent... ») ?", reference: "Une allitération" },
    { prompt: "Quel est le féminin de « directeur » ?", reference: "Directrice" },
    { prompt: "Quel mot invariable relie deux propositions : « et », « ou », « mais »... comment appelle-t-on ça ?", reference: "Une conjonction de coordination" },
    { prompt: "Quel est le participe présent du verbe « chanter » ?", reference: "Chantant" },
    { prompt: "Comment écrit-on le son [s] dans « garçon » ?", reference: "Avec une cédille (ç)" },
    { prompt: "Quel est l'antonyme de « acheter » ?", reference: "Vendre" },
    { prompt: "Quel est le pluriel de « œil » ?", reference: "Yeux" },
    { prompt: "Quel mode utilise-t-on pour donner un ordre : « Sors ! » ?", reference: "L'impératif" },
    { prompt: "Quel est le féminin de « roi » ?", reference: "Reine" },
    { prompt: "Comment appelle-t-on une phrase exclamative typique : « Quelle belle journée ! » ?", reference: "Une phrase exclamative" },
    { prompt: "Quel est le synonyme de « content » ?", reference: "Heureux (ou joyeux)" },
    { prompt: "« Ils se sont lavés » : pourquoi le participe passé s'accorde-t-il ici ?", reference: "Verbe pronominal, l'action est réfléchie sur le sujet (COD placé avant)" },
    { prompt: "Quel est le contraire de « commencer » ?", reference: "Finir (ou terminer)" },
    { prompt: "Quel est le pluriel de « bijou » ?", reference: "Bijoux" },
    { prompt: "Comment appelle-t-on un texte qui raconte une histoire à la 1ère personne, souvent autobiographique ?", reference: "Un récit à la première personne (ou autobiographie)" },
    { prompt: "Quel est l'homophone de « sont » qui indique la possession ?", reference: "Son" },
    { prompt: "Quel est le féminin de « époux » ?", reference: "Épouse" },
    { prompt: "Quel temps utilise-t-on pour une action qui vient de se terminer et a un lien avec le présent : « J'ai mangé » ?", reference: "Le passé composé" },
    { prompt: "Quel est le pluriel de « travail » ?", reference: "Travaux" },
    { prompt: "Comment appelle-t-on une exagération volontaire (« Je meurs de faim ») ?", reference: "Une hyperbole" },
    { prompt: "Quel est l'antonyme de « ouvrir » ?", reference: "Fermer" },
  ],

  /* ================= MARQUES & ENTREPRISES (par indices) ================= */
  marques: [
    { prompt: "Marque de sport allemande reconnaissable à ses trois bandes.", reference: "Adidas" },
    { prompt: "Marque de sport américaine avec un slogan « Just Do It » et un logo en forme de virgule.", reference: "Nike" },
    { prompt: "Constructeur automobile français au losange.", reference: "Renault" },
    { prompt: "Constructeur automobile allemand aux quatre anneaux entrelacés.", reference: "Audi" },
    { prompt: "Marque de smartphones américaine à la pomme croquée.", reference: "Apple" },
    { prompt: "Géant sud-coréen de l'électronique, aussi présent dans les smartphones.", reference: "Samsung" },
    { prompt: "Marque de boissons gazeuses américaine à la bouteille contour rouge et blanc.", reference: "Coca-Cola" },
    { prompt: "Chaîne de restauration rapide américaine avec un « M » jaune.", reference: "McDonald's" },
    { prompt: "Marque française de maroquinerie et mode de luxe fondée par un couturier au monogramme entrelacé.", reference: "Louis Vuitton" },
    { prompt: "Marque française de vêtements avec un petit crocodile brodé.", reference: "Lacoste" },
    { prompt: "Réseau social où l'on publie des photos, racheté par Meta.", reference: "Instagram" },
    { prompt: "Moteur de recherche le plus utilisé au monde.", reference: "Google" },
    { prompt: "Marque suédoise de meubles en kit à monter soi-même.", reference: "IKEA" },
    { prompt: "Constructeur automobile italien au cheval cabré, symbole du luxe sportif.", reference: "Ferrari" },
    { prompt: "Marque japonaise de jeux vidéo, créatrice de Mario et Zelda.", reference: "Nintendo" },
    { prompt: "Entreprise américaine de vente en ligne dont le logo a une flèche souriante de A à Z.", reference: "Amazon" },
    { prompt: "Marque française de yaourts et produits laitiers.", reference: "Danone" },
    { prompt: "Constructeur automobile japonais, l'un des plus vendus au monde.", reference: "Toyota" },
    { prompt: "Marque de café italienne à capsules fondée sous le nom d'une machine expresso.", reference: "Nespresso" },
    { prompt: "Réseau social au petit oiseau bleu, aujourd'hui renommé X.", reference: "Twitter (X)" },
    { prompt: "Marque allemande de chaussures et vêtements de sport à trois bandes, rivale historique de Nike.", reference: "Adidas" },
    { prompt: "Entreprise américaine créatrice du iPhone, du Mac et de l'iPad.", reference: "Apple" },
    { prompt: "Marque française de cosmétiques présente dans presque toutes les salles de bain, slogan « Parce que je le vaux bien ».", reference: "L'Oréal" },
    { prompt: "Chaîne de cafés américaine à la sirène verte.", reference: "Starbucks" },
    { prompt: "Marque de vêtements de sport allemande fondée par les frères Dassler (autre que la marque aux trois bandes).", reference: "Puma" },
    { prompt: "Marque automobile allemande au logo bleu et blanc évoquant une hélice d'avion.", reference: "BMW" },
    { prompt: "Marque de luxe française spécialisée dans les sacs à main, connue pour son carré de soie.", reference: "Hermès" },
    { prompt: "Plateforme de streaming vidéo au « N » rouge, connue pour ses séries originales.", reference: "Netflix" },
    { prompt: "Entreprise française de pneumatiques dont la mascotte est un bonhomme fait de pneus blancs.", reference: "Michelin" },
    { prompt: "Marque de matériel informatique et logiciels fondée par Bill Gates.", reference: "Microsoft" },
    { prompt: "Marque de restauration rapide américaine spécialisée dans le poulet frit, logo avec un vieux monsieur en costume.", reference: "KFC" },
    { prompt: "Constructeur automobile américain de véhicules électriques dirigé par Elon Musk.", reference: "Tesla" },
    { prompt: "Marque française de cosmétiques et parfums de luxe née d'une célèbre couturière aux initiales doublées.", reference: "Chanel" },
    { prompt: "Marque japonaise d'électronique et de jeux vidéo, créatrice de la PlayStation.", reference: "Sony" },
    { prompt: "Chaîne de fast-food française d'origine belge spécialisée dans le poulet.", reference: "Quick" },
  ],

  /* ================= CULTURE GÉNÉRALE ================= */
  culture_generale: [
    { prompt: "Combien de continents compte-t-on généralement ?", reference: "5 (ou 6/7 selon les découpages)" },
    { prompt: "Quelle est la monnaie utilisée au Japon ?", reference: "Le yen" },
    { prompt: "Quel est le plus grand océan du monde ?", reference: "L'océan Pacifique" },
    { prompt: "Combien de couleurs compte l'arc-en-ciel traditionnellement ?", reference: "7" },
    { prompt: "Quelle est la langue la plus parlée au monde (nombre de locuteurs natifs) ?", reference: "Le mandarin" },
    { prompt: "Quel est le symbole chimique de l'eau ?", reference: "H2O" },
    { prompt: "Combien de jours compte une année bissextile ?", reference: "366" },
    { prompt: "Quel pays a la forme d'une botte sur la carte d'Europe ?", reference: "L'Italie" },
    { prompt: "Quel est l'instrument de musique à 88 touches ?", reference: "Le piano" },
    { prompt: "Quelle planète est surnommée la « planète rouge » ?", reference: "Mars" },
    { prompt: "Combien de temps la Lune met-elle environ à tourner autour de la Terre ?", reference: "Environ 27 à 29 jours" },
    { prompt: "Quel est le plus long fleuve de France ?", reference: "La Loire" },
    { prompt: "Quel sport se joue à Wimbledon ?", reference: "Le tennis" },
    { prompt: "Combien de cordes compte une guitare classique ?", reference: "6" },
    { prompt: "Quelle est la capitale de l'Italie ?", reference: "Rome" },
    { prompt: "Quel est l'animal terrestre le plus rapide du monde ?", reference: "Le guépard" },
    { prompt: "Combien de faces possède un dé classique ?", reference: "6" },
    { prompt: "Quel gaz respirons-nous principalement pour vivre ?", reference: "L'oxygène" },
    { prompt: "Quelle est la capitale de l'Espagne ?", reference: "Madrid" },
    { prompt: "Combien de temps dure une olympiade ?", reference: "4 ans" },
    { prompt: "Quel est le plus petit os du corps humain ?", reference: "L'étrier (dans l'oreille)" },
    { prompt: "Quelle est la capitale du Japon ?", reference: "Tokyo" },
    { prompt: "Quel fruit est associé à Isaac Newton et la découverte de la gravité ?", reference: "La pomme" },
    { prompt: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", reference: "Environ 8 minutes" },
    { prompt: "Quelle est la capitale de l'Allemagne ?", reference: "Berlin" },
    { prompt: "Quel est le nom du satellite naturel de la Terre ?", reference: "La Lune" },
    { prompt: "Combien de pattes a une araignée ?", reference: "8" },
    { prompt: "Quelle est la plus grande île du monde ?", reference: "Le Groenland" },
    { prompt: "Quel métal précieux est symbolisé par « Au » ?", reference: "L'or" },
    { prompt: "Quel pays a inventé le sushi ?", reference: "Le Japon" },
    { prompt: "Quelle est la vitesse du son approximativement dans l'air ?", reference: "Environ 340 mètres par seconde" },
    { prompt: "Quel organe humain filtre le sang pour produire l'urine ?", reference: "Le rein" },
    { prompt: "Quelle est la capitale du Portugal ?", reference: "Lisbonne" },
    { prompt: "Combien de dents a un adulte en moyenne ?", reference: "32" },
    { prompt: "Quel est le plus grand désert froid du monde ?", reference: "L'Antarctique" },
    { prompt: "Quelle est la monnaie utilisée au Royaume-Uni ?", reference: "La livre sterling" },
    { prompt: "Quel est l'organe principal du système nerveux ?", reference: "Le cerveau" },
    { prompt: "Combien de zéros comporte un million écrit en chiffres ?", reference: "6" },
    { prompt: "Quelle est la capitale de la Russie ?", reference: "Moscou" },
    { prompt: "Quel animal est le meilleur ami de l'homme, selon l'expression ?", reference: "Le chien" },
    { prompt: "Quel est le plus haut sommet d'Europe ?", reference: "Le mont Elbrouz (ou le Mont Blanc pour l'Europe de l'Ouest)" },
    { prompt: "Combien de continents la Russie chevauche-t-elle ?", reference: "2 (Europe et Asie)" },
    { prompt: "Quel est le plus grand pays d'Afrique par la population ?", reference: "Le Nigeria" },
    { prompt: "Quelle est la capitale des États-Unis ?", reference: "Washington D.C." },
    { prompt: "Quel est le symbole chimique du sel de table ?", reference: "NaCl" },
    { prompt: "Quelle est la couleur obtenue en mélangeant le bleu et le jaune ?", reference: "Le vert" },
    { prompt: "Quel est le plus grand mammifère marin ?", reference: "La baleine bleue" },
    { prompt: "Combien de minutes dure un match de basketball NBA hors prolongations ?", reference: "48 minutes" },
    { prompt: "Quel est le nom de la galaxie qui contient notre système solaire ?", reference: "La Voie lactée" },
    { prompt: "Quelle est la capitale de la Chine ?", reference: "Pékin" },
  ],
};

const CATEGORY_LABELS = {
  animaux: "Animaux",
  petit_bac: "Petit Bac",
  rebus: "Rébus",
  histoire: "Histoire",
  grandes_figures: "Grandes figures & événements",
  francais: "Français",
  marques: "Marques (indices)",
  culture_generale: "Culture générale",
};

// Rend la banque accessible en tant que module (utilisée par app.js)
if (typeof module !== 'undefined') { module.exports = QUESTION_BANK; }
if (typeof window !== 'undefined') { window.QUESTION_BANK = QUESTION_BANK; window.CATEGORY_LABELS = CATEGORY_LABELS; }