/* ============================================================
   A&M QUIZZ — BANQUE DE QUESTIONS
   ------------------------------------------------------------
   Chaque question a la forme :
   { category, type, prompt, image (optionnel), reference (optionnel) }
 
   - "reference" = la réponse attendue, affichée à l'hôte ET à tous
     les joueurs pendant la phase de correction (sauf pour le petit
     bac, où "reference" contient juste des EXEMPLES pour aider
     l'hôte à juger, pas LA réponse).
   - L'hôte valide chaque réponse joueur par Vrai/Faux, quelle que
     soit la catégorie : c'est un choix demandé explicitement (jeu
     entre amis, pas de correction automatique rigide).
 
   POUR AJOUTER DES QUESTIONS : copie une ligne existante de la
   catégorie voulue et remplace le contenu. Aucune limite de taille.
   ============================================================ */
 
/* NOTE (fix) : quand "Petit Bac" est sélectionné seul (sans autre catégorie),
   on peut piocher jusqu'au nombre de questions demandé (et non plafonné à 3),
   sinon il reste un "round" limité mélangé aux autres catégories. Voir app.js. */
const QUESTION_BANK = {
 
  /* ================= ANIMAUX (à deviner) ================= */
  // Affichées via un gros emoji (fiable, pas de lien image cassé).
  // Remplace "image" par une vraie URL de photo si tu veux.
  animaux: [
    { prompt: "Quel est cet animal ?", image: "https://cdn-images.zoobeauval.com/pTsc7axkqY3t5MzSk0WS5C3K7Ig=/730x730/https%3A%2F%2Fs3.eu-west-3.amazonaws.com%2Fimages.zoobeauval.com%2F2024%2F02%2Fgirafe-02-65ccbbb1cfc0b.jpg", reference: "Girafe" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Lion_d%27Afrique.jpg", reference: "Lion" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/3/37/African_Bush_Elephant.jpg", reference: "Éléphant" },
    { prompt: "Quel est cet animal ?", image: "https://www.zoodejurques.fr/wp-content/uploads/2019/05/Jillian-Knox_Grevys-Zebra_305-fullsizeoutput_ce1d-1000x1000-c-center.jpg", reference: "Zèbre" },
    { prompt: "Quel est cet animal ?", image: "https://wildexpedition.com/wp-content/uploads/2024/09/DSCN7042.jpeg", reference: "Hippopotame" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Nile_crocodile_head.jpg", reference: "Crocodile" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21606/hibou-des-marais-1068x1200.jpg", reference: "Hibou" },
    { prompt: "Quel est cet animal ?", image: "https://zooecomuseum.ca/workspace/uploads/modules/pygargue-mobile-fr-1575566403.jpg", reference: "Aigle" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Madagascan_Flying_Fox_%28Pteropus_rufus%29_%28captive_specimen%29_%289674779460%29.jpg/330px-Madagascan_Flying_Fox_%28Pteropus_rufus%29_%28captive_specimen%29_%289674779460%29.jpg", reference: "Chauve-souris" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGLW5dQukkIUiH5DvPv9DiiSMdS8iR2h3h44F8aFYFW736HcndXKmfXgfx&s=10", reference: "Dauphin" },
    { prompt: "Quel est cet animal ?", image: "https://static.ocean.org/oceanorg/2026/02/Humpback-whale-shutterstock_1455196766-1005x670-1.jpg", reference: "Baleine" },
    { prompt: "Quel est cet animal ?", image: "https://animauxmarins.fr/wp-content/uploads/2023/06/grand-requin-marteau.jpg", reference: "Requin Marteau" },
    { prompt: "Quel est cet animal ?", image: "https://cdn-images.zoobeauval.com/lTt4TMwFmYnHjH6mYkbwBuFAD4U=/730x730/https%3A%2F%2Fs3.eu-west-3.amazonaws.com%2Fimages.zoobeauval.com%2F2025%2F07%2Ftortue-aldabra-01-687e0770c8cc1.jpg", reference: "Tortue" },
    { prompt: "Quel est cet animal ?", image: "https://www.navetteaixmarseille.com/wp-content/uploads/elementor/thumbs/herisson-r1dams0o70yrgejw8xbluxox6008kqnjd07qt7lgts.jpg", reference: "Hérisson" },
    { prompt: "Quel est cet animal ?", image: "https://wwf.ca/wp-content/uploads/2024/11/Original_WW1287619-1024x679.jpg", reference: "Loutre" },
    { prompt: "Quel est cet animal ?", image: "https://www.sciencesetavenir.fr/assets/img/2014/09/26/cover-r4x3w1200-57e153aea71a2-le-paresseux.jpg", reference: "Paresseux" },
    { prompt: "Quel est cet animal ?", image: "https://media.ouest-france.fr/v1/pictures/120627b1b5ce29c8281dab952a8b982c-8490513.jpg?width=1260&client_id=eds&sign=74ac0093649c2e9e018e33fff7c1aae13d43304fea0fd1a9e1991ec2238f180c", reference: "Kangourou" },
    { prompt: "Quel est cet animal ?", image: "https://cdn.britannica.com/26/162626-050-3534626F/Koala.jpg", reference: "Koala" },
    { prompt: "Quel est cet animal ?", image: "https://static.europe1.fr/var/europe1/storage/styles/image_750_422/public/media/image/2025/02/15/11/le-panda-geant-n-est-plus-en-danger-mais-reste-menace.jpg?itok=yGQuBPtR", reference: "Panda" },
    { prompt: "Quel est cet animal ?", image: "https://www.phiessences.com/images/product_images/original_images/dreamstime-Lama_754pixel.jpg", reference: "Lama" },
    { prompt: "Quel est cet animal ?", image: "https://www.snpn.com/wp-content/uploads/2022/12/photo_snpn_Cervus-elaphus-hor.png-1200x1200.jpg", reference: "Cerf Élaphe" },
    { prompt: "Quel est cet animal ?", image: "https://zoodyssee.fr/wp-content/uploads/2026/02/sanglier_interieur2.webp", reference: "Sanglier" },
    { prompt: "Quel est cet animal ?", image: "https://www.zoologiste.com/images/main/blaireau.jpg", reference: "Blaireau" },
    { prompt: "Quel est cet animal ?", image: "https://www.lechasseurfrancais.com/wp-content/uploads/2025/04/le-castor-deurope-fait-son-grand-retour-en-alsace.jpg", reference: "Castor" },
    { prompt: "Quel est cet animal ?", image: "https://www.autourdesanimaux.com/wp-content/uploads/races/2465/lg_flamant-rose_646dcc2908f77.webp?1", reference: "Flamant rose" },
    { prompt: "Quel est cet animal ?", image: "https://blooming-pets.com/wp-content/uploads/2025/09/Paon-Bleu-Pavo-Cristatus.png.webp", reference: "Paon" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ6tmwiVcLklUa_EKQUOdjXMh4ZxhRYKpfbCj-6S21bXXefmwPJrPA6MI&s=10", reference: "Perroquet" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Manchot_empereur.jpg", reference: "Manchot" },
    { prompt: "Quel est cet animal ?", image: "https://www.aquariumbiarritz.com/wp-content/uploads/2025/06/phoque-gris-aquarium-de-biarritz-delphine-pernaud-8-614x1024.jpg", reference: "Phoque" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21601/anatomie-externe-de-lescargot-848x514.jpg", reference: "Escargot" },
    { prompt: "Quel est cet animal ?", image: "https://cdn.prod.website-files.com/62321a3fcb1f1e70c916da25/64a300d0572f25f2be24798b_papillon-monarque-emergence20-topweb.jpg", reference: "Papillon" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21612/dessin-dabeille-domestique-848x836.jpg", reference: "Abeille" },
    { prompt: "Quel est cet animal ?", image: "https://primary.jwwb.nl/public/o/j/v/temp-hzihylvryzejjaqjmgne/img_20240712_163544-high.jpg?enable-io=true&enable=upscale&fit=bounds&width=1200", reference: "Araignée" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWV7pyzVfr8_6gK3ArhtXGvBVbXDqORYDIAV-Q9K5cLOgzN9Hes_HtAtuo&s=10", reference: "Scorpion" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/22505/AdobeStock_95634179-1800x1200.jpeg", reference: "Poulpe" },
    { prompt: "Quel est cet animal ?", image: "https://www.tastefrance.com/sites/default/files/2020-11/Calmar.jpg", reference: "Calamar" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/KreeftbijDenOsse.jpg", reference: "Homard" },
    { prompt: "Quel est cet animal ?", image: "https://www.oceanopolis.com/wp-content/uploads/2019/11/crabe-dormeur-cancer-pagurus-oceanopolis-800x533.jpg", reference: "Crabe" },
    { prompt: "Quel est cet animal ?", image: "https://image.jimcdn.com/app/cms/image/transf/dimension=420x10000:format=png/path/s5dde8bff85c81b2f/image/i27a521a2e37eecca/version/1642492557/chameau-image-animaux-transparent-sur-fond-blanc-pour-site-web-illustration-ecole-montessori.png", reference: "Chameau" },
    { prompt: "Quel est cet animal ?", image: "https://media.ooreka.fr/public/image/dinde-basse-cour-ferme-main-11910359.jpg", reference: "Dinde" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Red_Squirrel_-_Lazienki.JPG/330px-Red_Squirrel_-_Lazienki.JPG", reference: "Écureuil" },
    { prompt: "Quel animal est surnommé le « roi de la savane » ?", reference: "Le lion" },
    { prompt: "Quel est le plus grand animal terrestre actuel ?", reference: "L'éléphant d'Afrique" },
    { prompt: "Quel est le plus grand animal du monde (marin ou terrestre) ?", reference: "La baleine bleue" },
    { prompt: "Quel oiseau ne sait pas voler mais court très vite en Afrique ?", reference: "L'autruche" },
    { prompt: "Quel animal change de couleur pour se camoufler ?", reference: "Le caméléon" },
    { prompt: "Quel mammifère d'Australie pond des œufs ?", reference: "L'ornithorynque" },
    { prompt: "Quel est le seul mammifère capable de voler ?", reference: "La chauve-souris" },
    { prompt: "Quel oiseau marin a la plus grande envergure au monde ?", reference: "L'albatros" },
    { prompt: "Quel animal produit des excréments en forme de cube ?", reference: "Le wombat" },
    { prompt: "Quel reptile est capable de marcher sur l'eau et est surnommé 'lézard Jésus-Christ' ?", reference: "Le basilic" },
    { prompt: "Quel animal marin possède trois cœurs et un sang bleu ?", reference: "La pieuvre (ou poulpe)" },
    { prompt: "Quel est le serpent le plus venimeux du monde (qui vit en Australie) ?", reference: "Le taïpan du désert" },
    { prompt: "Quel insecte est connu pour transmettre le paludisme ?", reference: "Le moustique (l'anophèle)" },
    { prompt: "Quel oiseau est l'emblème national des États-Unis ?", reference: "Le pygargue à tête blanche" },
    { prompt: "Quel mammifère marin possède une longue défense torsadée rappelant une corne de licorne ?", reference: "Le narval" },
    { prompt: "Quel grand félin est le plus rapide à la course ?", reference: "Le guépard" },
    { prompt: "Quel singe de Bornéo est célèbre pour son très long nez ?", reference: "Le nasique" },
    { prompt: "Quel animal construit des barrages sur les rivières ?", reference: "Le castor" },
    { prompt: "Quel petit insecte rouge à points noirs porte-bonheur est le cauchemar des pucerons ?", reference: "La coccinelle" },
    { prompt: "Quel est le plus grand primate actuel ?", reference: "Le gorille" },
    { prompt: "Quel oiseau symbolise la paix, souvent représenté avec un rameau d'olivier ?", reference: "La colombe" },
    { prompt: "Quel canidé sauvage crie ou glapit et ressemble à un petit loup roux ?", reference: "Le renard" },
    { prompt: "Quel poisson possède une lumière au-dessus de la tête pour attirer ses proies dans les abysses ?", reference: "La baudroie (ou poisson-pêcheur)" },
    { prompt: "Quel amphibien d'Amérique centrale est extrêmement toxique et souvent très coloré ?", reference: "La grenouille dendrobate" },
    { prompt: "Quelle araignée est tristement célèbre pour son venin et le fait que la femelle mange parfois le mâle ?", reference: "La veuve noire" },
    { prompt: "Quel petit animal crache un liquide malodorant pour se défendre ?", reference: "La mouffette (ou sconse)" },
    { prompt: "Quel animal d'Amérique du Sud crache sur ses adversaires quand il est contrarié ?", reference: "Le lama" },
    { prompt: "Quel rongeur épineux se met en boule pour se protéger des prédateurs ?", reference: "Le hérisson" },
    { prompt: "Quel oiseau rapace nocturne tourne sa tête jusqu'à 270 degrés ?", reference: "La chouette (ou le hibou)" },
    { prompt: "Quel gros animal blanc vit sur la banquise de l'Arctique ?", reference: "L'ours polaire" },
  ],
 
  /* ================= DRAPEAUX ================= */
  drapeaux: [
    { prompt: "Quel est ce pays ?", image: "https://dekkade.com/1653-thickbox_default/drapeau-france.webp", reference: "France" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/langfr-250px-Flag_of_Germany.svg.png", reference: "Allemagne" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/langfr-250px-Bandera_de_Espa%C3%B1a.svg.png", reference: "Espagne" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg", reference: "Italie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Flag_of_Portugal_%28official%29.svg/1280px-Flag_of_Portugal_%28official%29.svg.png", reference: "Portugal" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg", reference: "Royaume-Uni" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg", reference: "États-Unis" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg", reference: "Canada" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1280px-Flag_of_Mexico.svg.png", reference: "Mexique" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg", reference: "Brésil" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg", reference: "Argentine" },
    { prompt: "Quel est ce pays ?", image: "https://www.kanpai.fr/sites/default/files/uploads/2012/03/drapeau-japonais.gif", reference: "Japon" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg", reference: "Chine" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/langfr-250px-Flag_of_South_Korea.svg.png", reference: "Corée du Sud" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/langfr-250px-Flag_of_India.svg.png", reference: "Inde" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg", reference: "Russie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg", reference: "Grèce" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg", reference: "Pays-Bas" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/langfr-250px-Flag_of_Belgium.svg.png", reference: "Belgique" },
    { prompt: "Quel est ce pays ?", image: "https://www.flagsonline.fr/uploads/2016-6-6/420-272/switzerland.jpg", reference: "Suisse" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg", reference: "Suède" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png", reference: "Norvège" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/langfr-250px-Flag_of_Denmark.svg.png", reference: "Danemark" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/langfr-250px-Flag_of_Poland.svg.png", reference: "Pologne" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg", reference: "Autriche" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/1280px-Flag_of_Ireland.svg.png", reference: "Irlande" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg", reference: "Turquie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg", reference: "Maroc" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg", reference: "Algérie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg", reference: "Tunisie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Flag_of_Egypt_%28darker_shade_of_gold%29.svg", reference: "Égypte" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/langfr-250px-Flag_of_South_Africa.svg.png", reference: "Afrique du Sud" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg", reference: "Nigeria" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg", reference: "Sénégal" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg", reference: "Australie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg", reference: "Nouvelle-Zélande" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg", reference: "Islande" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/langfr-250px-Flag_of_Finland.svg.png", reference: "Finlande" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg", reference: "Hongrie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg", reference: "République tchèque" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg", reference: "Ukraine" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg", reference: "Arabie saoudite" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg", reference: "Émirats arabes unis" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg", reference: "Thaïlande" },
    { prompt: "Quel est ce pays ?", image: "https://horizon-vietnamvoyage.com/wp-content/uploads/2025/10/le-drapeau-du-vietnam.png", reference: "Vietnam" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg", reference: "Indonésie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg", reference: "Philippines" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/langfr-250px-Flag_of_Colombia.svg.png", reference: "Colombie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg", reference: "Chili" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg", reference: "Cuba" },
    { prompt: "Quel est ce pays ?", image: "https://www.drapeauxdespays.fr/data/flags/w580/pe.png", reference: "Pérou" },
    { prompt: "Quel est ce pays ?", image: "https://media.magflags.net/media/catalog/product/cache/bbfe81b5dc693f3f88259968def067fa/C/R/CR-1x1.5_11.png", reference: "Costa Rica" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg", reference: "Jamaïque" },
    { prompt: "Quel est ce pays ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHfolZrhrnH_VxkxFhf3FT9qGidvGLXGcB8i5MDSNlgg&s=10", reference: "Uruguay" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg", reference: "Slovaquie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Civil_ensign_of_Croatia.svg/langfr-250px-Civil_ensign_of_Croatia.svg.png", reference: "Croatie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png", reference: "Serbie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/langfr-250px-Flag_of_Romania.svg.png", reference: "Roumanie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/langfr-250px-Flag_of_Bulgaria.svg.png", reference: "Bulgarie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg", reference: "Madagascar" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg", reference: "Kenya" },
    { prompt: "Quel est ce pays ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIq8UefFhsKHL-CrFex8_KwYGRblSXnpMMbiISJuQCGQ&s=10", reference: "Côte d'Ivoire" },
    { prompt: "Quel est ce pays ?", image: "https://www.flagsonline.fr/uploads/2016-6-6/420-272/cameroon.jpg", reference: "Cameroun" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg", reference: "Ghana" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg", reference: "Iran" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg", reference: "Israël" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg", reference: "Liban" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg", reference: "Pakistan" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg", reference: "Malaisie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg", reference: "Singapour" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg", reference: "Fidji" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg", reference: "Kazakhstan" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg", reference: "Bolivie" },
    { prompt: "Quel est ce pays ?", image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg", reference: "Équateur" },
  ],
 
  /* ================= HISTOIRE ================= */
  histoire: [
    { prompt: "En quelle année a eu lieu la prise de la Bastille ?", reference: "1789" },
    { prompt: "Quel empereur romain a légalisé le christianisme ?", reference: "Constantin" },
    { prompt: "Qui était le premier empereur des Français ?", reference: "Napoléon Bonaparte" },
    { prompt: "En quelle année a débuté la Première Guerre mondiale ?", reference: "1914" },
    { prompt: "Quel traité a mis fin à la Première Guerre mondiale ?", reference: "Le traité de Versailles" },
    { prompt: "Quelle civilisation a construit les pyramides de Gizeh ?", reference: "Les Égyptiens" },
    { prompt: "Qui a lancé l'appel du 18 juin 1940 ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année le mur de Berlin est-il tombé ?", reference: "1989" },
    { prompt: "Quel roi de France est surnommé le « Roi Soleil » ?", reference: "Louis XIV" },
    { prompt: "Quelle bataille marque la défaite finale de Napoléon en 1815 ?", reference: "Waterloo" },
    { prompt: "Qui a dirigé l'URSS pendant la majeure partie de la Seconde Guerre mondiale ?", reference: "Staline" },
    { prompt: "Quelle bataille de 1916 est un symbole de l'enfer des tranchées ?", reference: "Verdun" },
    { prompt: "Quel événement déclenche directement la Première Guerre mondiale ?", reference: "L'assassinat de l'archiduc François-Ferdinand" },
    { prompt: "En quelle année Hitler prend-il le pouvoir en Allemagne ?", reference: "1933" },
    { prompt: "Quelle opération du 6 juin 1944 marque le début de la libération de la France ?", reference: "Le débarquement de Normandie (Overlord)" },
    { prompt: "Qui était le chef de l'État français de Vichy ?", reference: "Philippe Pétain" },
    { prompt: "En quelle année la Seconde Guerre mondiale se termine-t-elle ?", reference: "1945" },
    { prompt: "Quel roi de France a été guillotiné en 1793 ?", reference: "Louis XVI" },
    { prompt: "Quelle est la date symbolique du début de la Révolution française ?", reference: "14 juillet 1789" },
    { prompt: "Quel pays envahit la Pologne en septembre 1939 ?", reference: "L'Allemagne nazie" },
    { prompt: "Quel accord de 1938 cède les Sudètes à Hitler ?", reference: "Les accords de Munich" },
    { prompt: "Quelle organisation est créée en 1945 pour maintenir la paix mondiale ?", reference: "L'ONU" },
    { prompt: "Quel événement de 1917 fait sortir la Russie de la guerre ?", reference: "La révolution russe" },
    { prompt: "Qui a été le premier président de la Ve République ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année Christophe Colomb atteint-il l'Amérique ?", reference: "1492" },
    { prompt: "Quel empire romain tombe en 476 ?", reference: "L'Empire romain d'Occident" },
    { prompt: "Quelle reine d'Égypte est célèbre pour sa liaison avec César puis Marc Antoine ?", reference: "Cléopâtre" },
    { prompt: "Quel mur sépare Berlin-Est et Berlin-Ouest de 1961 à 1989 ?", reference: "Le mur de Berlin" },
    { prompt: "Quelle guerre oppose le Nord et le Sud des États-Unis (1861-1865) ?", reference: "La guerre de Sécession" },
    { prompt: "Quel navire britannique coule en 1912 après avoir heurté un iceberg ?", reference: "Le Titanic" },
    { prompt: "Quel pharaon égyptien est célèbre pour son masque funéraire en or ?", reference: "Toutankhamon" },
    { prompt: "Quelle bataille de 1815 se déroule en Belgique actuelle ?", reference: "Waterloo" },
    { prompt: "Quel roi anglais signe la Magna Carta en 1215 ?", reference: "Jean sans Terre" },
    { prompt: "Quelle épidémie décime l'Europe au XIVe siècle ?", reference: "La peste noire" },
    { prompt: "Quel explorateur portugais réalise le premier tour du monde (expédition achevée après sa mort) ?", reference: "Magellan" },
    { prompt: "En quelle année la France abolit-elle l'esclavage pour la seconde fois (définitivement) ?", reference: "1848" },
    { prompt: "Quel événement déclenche la Terreur en France en 1793 ?", reference: "L'exécution du roi et la guerre contre les monarchies européennes" },
    { prompt: "Quel traité de 1648 met fin à la guerre de Trente Ans ?", reference: "La paix de Westphalie" },
    { prompt: "Quelle civilisation antique a inventé la démocratie ?", reference: "Les Grecs (Athènes)" },
    { prompt: "Quel dirigeant chinois fonde la République populaire de Chine en 1949 ?", reference: "Mao Zedong" },
    { prompt: "Qui a inventé l'imprimerie à caractères mobiles en Europe vers 1450 ?", reference: "Gutenberg" },
    { prompt: "En quelle année l'Empire romain d'Orient (Byzance) a-t-il chuté ?", reference: "1453" },
    { prompt: "Quel président américain a aboli l'esclavage pendant la guerre de Sécession ?", reference: "Abraham Lincoln" },
    { prompt: "Comment s'appelait le premier engin spatial à envoyer un homme dans l'espace en 1961 ?", reference: "Vostok 1 (avec Youri Gagarine)" },
    { prompt: "Quel nom donnait-on aux guerriers scandinaves qui ont mené des raids en Europe du VIIIe au XIe siècle ?", reference: "Les Vikings" },
    { prompt: "De quel pays actuel est originaire la civilisation maya ?", reference: "Le Mexique (ou Guatemala/Belize)" },
    { prompt: "En quelle année a été signée la Déclaration d'indépendance des États-Unis ?", reference: "1776" },
    { prompt: "Qui était le roi des Francs couronné empereur en l'an 800 ?", reference: "Charlemagne" },
    { prompt: "Quelle guerre a opposé la France et l'Angleterre de 1337 à 1453 ?", reference: "La guerre de Cent Ans" },
    { prompt: "Comment appelait-on la période de forte tension entre les États-Unis et l'URSS après 1945 ?", reference: "La Guerre froide" },
    { prompt: "Quel général a pris le pouvoir à Rome en franchissant le Rubicon ?", reference: "Jules César" },
    { prompt: "Quel célèbre code de lois a été promulgué par Napoléon en 1804 ?", reference: "Le Code civil (ou Code Napoléon)" },
    { prompt: "Dans quelle ville Jeanne d'Arc a-t-elle été brûlée vive en 1431 ?", reference: "Rouen" },
    { prompt: "Quel mouvement intellectuel et culturel a marqué l'Europe au XVIIIe siècle ?", reference: "Les Lumières" },
    { prompt: "Qui a découvert la pénicilline en 1928 ?", reference: "Alexander Fleming" },
    { prompt: "Quelle bataille navale de 1805 a vu la victoire de l'amiral Nelson sur la flotte franco-espagnole ?", reference: "Trafalgar" },
    { prompt: "Quel pays a subi les bombardements atomiques de Hiroshima et Nagasaki en 1945 ?", reference: "Le Japon" },
    { prompt: "Comment s'appelait le réseau de routes commerciales reliant la Chine à l'Europe dans l'Antiquité et au Moyen Âge ?", reference: "La route de la soie" },
    { prompt: "Quel révolutionnaire argentin a aidé Fidel Castro lors de la révolution cubaine ?", reference: "Che Guevara" },
    { prompt: "Qui a été le premier président de la République française en 1848 ?", reference: "Louis-Napoléon Bonaparte" },
    { prompt: "Quelle célèbre prison de Paris a été prise d'assaut le 14 juillet 1789 ?", reference: "La Bastille" },
    { prompt: "En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée en France ?", reference: "1905" },
    { prompt: "Quel conflit a opposé le Viêt Nam du Nord, soutenu par l'URSS, au Sud, soutenu par les USA ?", reference: "La guerre du Viêt Nam" },
    { prompt: "Qui était la célèbre infirmière britannique pionnière des soins modernes pendant la guerre de Crimée ?", reference: "Florence Nightingale" },
    { prompt: "Comment s'appelait l'alliance militaire dirigée par l'URSS pendant la Guerre froide ?", reference: "Le Pacte de Varsovie" },
  ],
 
  /* ================= GRANDES FIGURES & ÉVÉNEMENTS ================= */
  grandes_figures: [
    { prompt: "Je suis une jeune paysanne qui a mené l'armée française à Orléans avant d'être brûlée vive. Qui suis-je ?", reference: "Jeanne d'Arc" },
    { prompt: "Je suis un physicien qui a formulé la théorie de la relativité. Qui suis-je ?", reference: "Albert Einstein" },
    { prompt: "Je suis un pasteur américain qui a prononcé le discours « I have a dream ». Qui suis-je ?", reference: "Martin Luther King" },
    { prompt: "Je suis une reine d'Égypte, dernière souveraine de la dynastie ptolémaïque. Qui suis-je ?", reference: "Cléopâtre" },
    { prompt: "Je suis un général qui a lancé l'appel du 18 juin 1940 depuis Londres. Qui suis-je ?", reference: "Charles de Gaulle" },
    { prompt: "Je suis un chef d'État sud-africain emprisonné 27 ans avant de devenir président. Qui suis-je ?", reference: "Nelson Mandela" },
    { prompt: "Je suis une scientifique polonaise, seule personne à avoir reçu deux prix Nobel dans deux domaines différents. Qui suis-je ?", reference: "Marie Curie" },
    { prompt: "Je suis un roi de France qui a régné plus de 70 ans, le plus long règne de l'histoire de France. Qui suis-je ?", reference: "Louis XIV" },
    { prompt: "Je suis un dictateur allemand responsable de la Seconde Guerre mondiale et de la Shoah. Qui suis-je ?", reference: "Adolf Hitler" },
    { prompt: "Je suis un premier ministre britannique qui a résisté aux nazis pendant la bataille d'Angleterre. Qui suis-je ?", reference: "Winston Churchill" },
    { prompt: "Je suis un empereur romain qui a légalisé le christianisme. Qui suis-je ?", reference: "Constantin" },
    { prompt: "Je suis un navigateur qui a atteint l'Amérique en 1492 en cherchant une route vers les Indes. Qui suis-je ?", reference: "Christophe Colomb" },
    { prompt: "Je suis une résistante et ministre française, rescapée des camps, dont le visage est sur les manuels d'histoire. Qui suis-je ?", reference: "Simone Veil" },
    { prompt: "Je suis un philosophe grec, maître de Platon devenu maître d'Aristote lui-même. Qui suis-je ?", reference: "Socrate" },
    { prompt: "Je suis un leader indien qui a mené la résistance non-violente contre la colonisation britannique. Qui suis-je ?", reference: "Gandhi" },
    { prompt: "Je suis un tsar russe qui a modernisé la Russie et fondé Saint-Pétersbourg. Qui suis-je ?", reference: "Pierre le Grand" },
    { prompt: "Je suis une figure de la Résistance française, chargé par de Gaulle d'unifier les mouvements clandestins. Qui suis-je ?", reference: "Jean Moulin" },
    { prompt: "Je suis un roi macédonien qui a conquis un immense empire jusqu'en Inde avant 33 ans. Qui suis-je ?", reference: "Alexandre le Grand" },
    { prompt: "Je suis un président américain assassiné à Dallas en 1963. Qui suis-je ?", reference: "John F. Kennedy" },
    { prompt: "Je suis un empereur romain connu pour avoir conquis la Gaule. Qui suis-je ?", reference: "Jules César" },
    { prompt: "Je suis un inventeur américain à qui l'on attribue l'ampoule électrique. Qui suis-je ?", reference: "Thomas Edison" },
    { prompt: "Je suis une reine de France, épouse de Louis XVI, guillotinée en 1793. Qui suis-je ?", reference: "Marie-Antoinette" },
    { prompt: "Je suis un peintre néerlandais connu pour m'être coupé l'oreille. Qui suis-je ?", reference: "Vincent van Gogh" },
    { prompt: "Je suis le premier homme à avoir marché sur la Lune, en 1969. Qui suis-je ?", reference: "Neil Armstrong" },
    { prompt: "Je suis un chef militaire carthaginois qui a traversé les Alpes avec des éléphants. Qui suis-je ?", reference: "Hannibal Barca" },
    { prompt: "Je suis un compositeur allemand devenu sourd qui a continué à composer. Qui suis-je ?", reference: "Ludwig van Beethoven" },
    { prompt: "Je suis un moine allemand à l'origine de la Réforme protestante. Qui suis-je ?", reference: "Martin Luther" },
    { prompt: "Je suis un pharaon dont la tombe intacte a été découverte en 1922 par Howard Carter. Qui suis-je ?", reference: "Toutankhamon" },
    { prompt: "Je suis une aviatrice américaine disparue en 1937 en tentant de faire le tour du monde. Qui suis-je ?", reference: "Amelia Earhart" },
    { prompt: "Je suis un écrivain et aviateur français, auteur du « Petit Prince », disparu en vol en 1944. Qui suis-je ?", reference: "Antoine de Saint-Exupéry" },
    { prompt: "Je suis un chef d'État soviétique à l'origine de la Révolution d'Octobre 1917. Qui suis-je ?", reference: "Lénine" },
    { prompt: "Je suis un savant italien condamné par l'Église pour avoir défendu que la Terre tourne autour du Soleil. Qui suis-je ?", reference: "Galilée" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/T107mtZS/AC.png", reference: "Acacio" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/ygpyGbKL/boschman.png", reference: "Boschman" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/vx1twt8h/dada.png", reference: "Adem" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/y3JyCy6h/deloeil.jpg", reference: "Tyméo/Deloeil" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/xNk3V3jv/Maxime.png", reference: "Tiropijon" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/MfcmJmZs/Simon.png", reference: "Simon" },
    { prompt: "Je suis un dramaturge français du XVIIe siècle, auteur de 'L'Avare' et 'Le Tartuffe'. Qui suis-je ?", reference: "Molière" },
    { prompt: "Je suis une militante noire américaine qui a refusé de céder sa place dans un bus en 1955. Qui suis-je ?", reference: "Rosa Parks" },
    { prompt: "Je suis le scientifique français qui a mis au point le vaccin contre la rage. Qui suis-je ?", reference: "Louis Pasteur" },
    { prompt: "Je suis l'artiste de la Renaissance qui a peint La Joconde. Qui suis-je ?", reference: "Léonard de Vinci" },
    { prompt: "Je suis un célèbre écrivain français, auteur des 'Misérables' et de 'Notre-Dame de Paris'. Qui suis-je ?", reference: "Victor Hugo" },
    { prompt: "Je suis le cosmonaute soviétique qui fut le premier homme dans l'espace. Qui suis-je ?", reference: "Youri Gagarine" },
    { prompt: "Je suis une adolescente juive célèbre pour le journal intime que j'ai tenu cachée pendant la Seconde Guerre mondiale. Qui suis-je ?", reference: "Anne Frank" },
    { prompt: "Je suis l'inventeur du courant alternatif et grand rival de Thomas Edison. Qui suis-je ?", reference: "Nikola Tesla" },
    { prompt: "Je suis le génie autrichien de la musique classique, compositeur de 'La Flûte enchantée'. Qui suis-je ?", reference: "Wolfgang Amadeus Mozart" },
    { prompt: "Je suis une mère catholique albano-indienne, prix Nobel de la paix pour mon œuvre à Calcutta. Qui suis-je ?", reference: "Mère Teresa" },
    { prompt: "Je suis le fondateur de Microsoft et l'un des hommes les plus riches du monde. Qui suis-je ?", reference: "Bill Gates" },
    { prompt: "Je suis le cofondateur d'Apple et j'ai révolutionné la technologie avec l'iPhone. Qui suis-je ?", reference: "Steve Jobs" },
    { prompt: "Je suis un boxeur de légende, célèbre pour ma phrase 'Vole comme un papillon, pique comme une abeille'. Qui suis-je ?", reference: "Muhammad Ali (ou Cassius Clay)" },
    { prompt: "Je suis l'actrice emblématique blonde d'Hollywood dans les années 50, star de 'Certains l'aiment chaud'. Qui suis-je ?", reference: "Marilyn Monroe" },
    { prompt: "Je suis un révolutionnaire sud-américain qui a libéré plusieurs pays de la domination espagnole au XIXe siècle. Qui suis-je ?", reference: "Simón Bolívar" },
    { prompt: "Je suis un acteur britannique célèbre pour mon rôle de vagabond (Charlot) au cinéma muet. Qui suis-je ?", reference: "Charlie Chaplin" },
    { prompt: "Je suis le premier explorateur à avoir atteint le pôle Sud en 1911. Qui suis-je ?", reference: "Roald Amundsen" },
    { prompt: "Je suis une femme politique britannique surnommée la 'Dame de fer'. Qui suis-je ?", reference: "Margaret Thatcher" },
    { prompt: "Je suis le peintre espagnol cofondateur du cubisme, auteur de 'Guernica'. Qui suis-je ?", reference: "Pablo Picasso" },
    { prompt: "Je suis le fondateur du bouddhisme. Qui suis-je ?", reference: "Siddhartha Gautama (Le Bouddha)" },
    { prompt: "Je suis une figure mythique anglaise qui volait aux riches pour donner aux pauvres. Qui suis-je ?", reference: "Robin des Bois" },
    { prompt: "Je suis le physicien britannique célèbre pour mes travaux sur les trous noirs et mon livre 'Une brève histoire du temps'. Qui suis-je ?", reference: "Stephen Hawking" },
    { prompt: "Je suis le romancier britannique qui a créé le personnage de Sherlock Holmes. Qui suis-je ?", reference: "Arthur Conan Doyle" },
    { prompt: "Je suis l'ingénieur français qui a conçu la célèbre tour de fer à Paris pour l'Exposition universelle de 1889. Qui suis-je ?", reference: "Gustave Eiffel" },
    { prompt: "Je suis un philosophe et mathématicien français du XVIIe siècle, célèbre pour la phrase 'Je pense, donc je suis'. Qui suis-je ?", reference: "René Descartes" },
  ],
 
  /* ================= FRANÇAIS ================= */
  francais: [
    { prompt: "Quel est le féminin de « loup » ?", reference: "Louve" },
    { prompt: "Conjuguez « aller » à la 1ère personne du singulier au futur simple.", reference: "J'irai" },
    { prompt: "Quel est le pluriel de « cheval » ?", reference: "Chevaux" },
    { prompt: "Comment appelle-t-on une figure de style qui compare deux éléments avec « comme » ?", reference: "Une comparaison" },
    { prompt: "Quel est l'antonyme de « heureux » ?", reference: "Malheureux (ou triste)" },
    { prompt: "Combien de « p » y a-t-il dans le mot « appartement » ?", reference: "Deux" },
    { prompt: "Quel est le participe passé du verbe « prendre » ?", reference: "Pris" },
    { prompt: "Comment appelle-t-on une phrase qui pose une question ?", reference: "Une phrase interrogative" },
    { prompt: "Quel est le contraire de « monter » ?", reference: "Descendre" },
    { prompt: "« Cet homme est plus grand que moi » : quel est le mot qui exprime la comparaison ?", reference: "Plus... que" },
    { prompt: "Quel est le féminin de « acteur » ?", reference: "Actrice" },
    { prompt: "Comment écrit-on correctement : « malgré que » ou « bien que » est correct grammaticalement ?", reference: "Bien que" },
    { prompt: "Quel est l'homophone de « ver » qui désigne la couleur ?", reference: "Vert" },
    { prompt: "Quel temps exprime une action habituelle dans le passé : « Il jouait tous les jours » ?", reference: "L'imparfait" },
    { prompt: "Quel est le synonyme de « rapide » ?", reference: "Vite (ou véloce)" },
    { prompt: "Comment appelle-t-on un mot qui a le même sens qu'un autre ?", reference: "Un synonyme" },
    { prompt: "Quel est le pluriel de « journal » ?", reference: "Journaux" },
    { prompt: "« Je mange » à quelle personne et quel temps ?", reference: "1ère personne du singulier, présent" },
    { prompt: "Quel est l'antonyme de « facile » ?", reference: "Difficile" },
    { prompt: "Comment appelle-t-on la répétition d'un son en début de mots proches (« Pour qui sont ces serpents qui sifflent... ») ?", reference: "Une allitération" },
    { prompt: "Quel est le féminin de « directeur » ?", reference: "Directrice" },
    { prompt: "Quel mot invariable relie deux propositions : « et », « ou », « mais »... comment appelle-t-on ça ?", reference: "Une conjonction de coordination" },
    { prompt: "Quel est le participe présent du verbe « chanter » ?", reference: "Chantant" },
    { prompt: "Comment écrit-on le son [s] dans « garçon » ?", reference: "Avec une cédille (ç)" },
    { prompt: "Quel est l'antonyme de « acheter » ?", reference: "Vendre" },
    { prompt: "Quel est le pluriel de « œil » ?", reference: "Yeux" },
    { prompt: "Quel mode utilise-t-on pour donner un ordre : « Sors ! » ?", reference: "L'impératif" },
    { prompt: "Quel est le féminin de « roi » ?", reference: "Reine" },
    { prompt: "Comment appelle-t-on une phrase exclamative typique : « Quelle belle journée ! » ?", reference: "Une phrase exclamative" },
    { prompt: "Quel est le synonyme de « content » ?", reference: "Heureux (ou joyeux)" },
    { prompt: "« Ils se sont lavés » : pourquoi le participe passé s'accorde-t-il ici ?", reference: "Verbe pronominal, l'action est réfléchie sur le sujet (COD placé avant)" },
    { prompt: "Quel est le contraire de « commencer » ?", reference: "Finir (ou terminer)" },
    { prompt: "Quel est le pluriel de « bijou » ?", reference: "Bijoux" },
    { prompt: "Comment appelle-t-on un texte qui raconte une histoire à la 1ère personne, souvent autobiographique ?", reference: "Un récit à la première personne (ou autobiographie)" },
    { prompt: "Quel est l'homophone de « sont » qui indique la possession ?", reference: "Son" },
    { prompt: "Quel est le féminin de « époux » ?", reference: "Épouse" },
    { prompt: "Quel temps utilise-t-on pour une action qui vient de se terminer et a un lien avec le présent : « J'ai mangé » ?", reference: "Le passé composé" },
    { prompt: "Quel est le pluriel de « travail » ?", reference: "Travaux" },
    { prompt: "Comment appelle-t-on une exagération volontaire (« Je meurs de faim ») ?", reference: "Une hyperbole" },
    { prompt: "Quel est l'antonyme de « ouvrir » ?", reference: "Fermer" },
    { prompt: "Quel est le pluriel du mot 'chou' ?", reference: "Choux" },
    { prompt: "Comment s'écrit le participe passé du verbe 'résoudre' (au masculin singulier) ?", reference: "Résolu" },
    { prompt: "Quelle figure de style oppose deux mots de sens contraire juxtaposés (ex: 'Cette obscure clarté') ?", reference: "Un oxymore" },
    { prompt: "Quel est l'antonyme du mot 'optimiste' ?", reference: "Pessimiste" },
    { prompt: "Comment appelle-t-on un mot qui se lit dans les deux sens, comme 'radar' ou 'kayak' ?", reference: "Un palindrome" },
    { prompt: "Conjuguez le verbe 'avoir' à la 1ère personne du pluriel au conditionnel présent.", reference: "Nous aurions" },
    { prompt: "Quel est le féminin de 'neveu' ?", reference: "Nièce" },
    { prompt: "Complétez l'expression : 'Vendre la peau de l'...' ?", reference: "Ours" },
    { prompt: "Quelle est la racine grecque du mot 'chronomètre' qui signifie 'temps' ?", reference: "Chrono" },
    { prompt: "Comment appelle-t-on la ponctuation '...' ?", reference: "Les points de suspension" },
    { prompt: "Quel est le pluriel du mot 'vitrail' ?", reference: "Vitraux" },
    { prompt: "Quelle figure de style attribue des caractéristiques humaines à un objet ou un animal ?", reference: "La personnification" },
    { prompt: "Dans la phrase 'La pomme est mangée par Paul', la voix est-elle active ou passive ?", reference: "Passive" },
    { prompt: "Quel est l'infinitif du verbe conjugué dans : 'Il s'assit' ?", reference: "S'asseoir" },
    { prompt: "Combien de syllabes compte le mot 'indivisibilité' ?", reference: "7" },
    { prompt: "Quel est le contraire de 'généreux' ?", reference: "Avare (ou radin / égoïste)" },
    { prompt: "Comment appelle-t-on un vers de 12 syllabes en poésie ?", reference: "Un alexandrin" },
    { prompt: "Trouvez l'intrus parmi les synonymes : joyeux, ravi, morose, enchanté.", reference: "Morose" },
    { prompt: "Quel pronom relatif complète la phrase : 'C'est le livre ___ j'ai besoin' ?", reference: "Dont" },
    { prompt: "Comment écrit-on le chiffre 80 en lettres ?", reference: "Quatre-vingts (avec le s)" },
    { prompt: "Quel est le nom qui désigne l'étude des mots et de leur origine ?", reference: "L'étymologie" },
    { prompt: "Quel est le singulier de 'les cieux' ?", reference: "Le ciel" },
    { prompt: "Quelle préposition suit le verbe 'penser' pour désigner une personne ('Je pense ___ lui') ?", reference: "À" },
    { prompt: "Dans 'Elle a les yeux bleus', quelle est la classe grammaticale de 'bleus' ?", reference: "Adjectif qualificatif" },
    { prompt: "Que signifie l'acronyme T.V.A. ?", reference: "Taxe sur la Valeur Ajoutée" },
  ],
 
  /* ================= MARQUES & ENTREPRISES (par indices) ================= */
  marques: [
    { prompt: "Quel est cette marque ?", image: "https://lb-prod.fr/cdn/shop/articles/Capture_d_ecran_2023-03-07_155504.png?v=1678200918", reference: "Adidas" },
    { prompt: "Quel est cette marque ?", image: "https://www.pixartprinting.it/blog/wp-content/uploads/2023/12/1995-1024x561.jpg", reference: "Nike" },
    { prompt: "Quel est cette marque ?", image: "https://assets.renaultgroup.com/uploads/2021/03/nouveau_logo_renault.jpg?format=webp&width=3840", reference: "Renault" },
    { prompt: "Quel est cette marque ?", image: "https://uploads.audi.com/system/production/media/116125/images/74022a65b478f7b3a8e0bf8ba70994f66fde5dd7/A231415_web_2880.jpg?1698528985", reference: "Audi" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTb4lvXVxmncUmXkmc_lMQRh4s3AqtMHxtlkYHU2wAqA&s=10", reference: "Apple" },
    { prompt: "Quel est cette marque ?", image: "https://guide-images.cdn.ifixit.com/igi/TANXpRsbOhvSlC5A.medium", reference: "Samsung" },
    { prompt: "Quel est cette marque ?", image: "https://www.danstapub.com/wp-content/uploads/2015/07/dans-ta-pub-coca-cola-the-first-ever-no-labels-media-promo-design-pr-3.jpg", reference: "Coca-Cola" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/e/ea/Mcdonalds_France_2009_logo.svg/3840px-Mcdonalds_France_2009_logo.svg.png", reference: "McDonald's" },
    { prompt: "Quel est cette marque ?", image: "https://static.vecteezy.com/ti/vecteur-libre/p1/21608791-louis-vuitton-logo-louis-vuitton-icone-sur-marron-contexte-gratuit-vectoriel.jpg", reference: "Louis Vuitton" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2020/04/Lacoste-Embl%C3%A8me.jpg", reference: "Lacoste" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png", reference: "Instagram" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_%22G%22_logo.svg/3840px-Google_%22G%22_logo.svg.png", reference: "Google" },
    { prompt: "Quel est cette marque ?", image: "https://ih1.redbubble.net/image.5585518331.4410/st,small,507x507-pad,600x600,f8f8f8.u2.jpg", reference: "IKEA" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c0/Scuderia_Ferrari_Logo.svg/1920px-Scuderia_Ferrari_Logo.svg.png", reference: "Ferrari" },
    { prompt: "Quel est cette marque ?", image: "https://img.icons8.com/color/1200/nintendo-switch-logo.jpg", reference: "Nintendo Switch" },
    { prompt: "Quel est cette marque ?", image: "https://static.vecteezy.com/system/resources/thumbnails/019/766/223/small/amazon-logo-amazon-icon-transparent-free-png.png", reference: "Amazon" },
    { prompt: "Quel est cette marque ?", image: "https://img.lemde.fr/2017/06/22/7/0/276/137/1342/671/60/0/8e068ea_28878-y9u3wo.vt083680k9.PNG", reference: "Danone" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2022/05/Toyota-logo.png", reference: "Toyota" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Monogramme_Nespresso.png/250px-Monogramme_Nespresso.png", reference: "Nespresso" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2025/04/X-Logo.jpg", reference: "Twitter (X)" },
    { prompt: "Quel est cette marque ?", image: "https://cdn-icons-png.flaticon.com/512/5968/5968613.png", reference: "L'Oréal" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTONbMWa0xoap84mP0TcfclTnxmsjDnmjEkRkauTVYYSA&s=10", reference: "Starbucks" },
    { prompt: "Quel est cette marque ?", image: "https://assets.turbologo.com/blog/fr/2019/11/19134135/puma-logo-cover.png", reference: "Puma" },
    { prompt: "Quel est cette marque ?", image: "https://www.decoracing.com/366-large_default/bmw-sticker-logo-classique-bmw-m.jpg", reference: "BMW" },
    { prompt: "Quel est cette marque ?", image: "https://decoglam.net/storage/images/image?remote=https%3A%2F%2Fdecoglam.net%2FWebRoot%2FStore20%2FShops%2F57b2465e-10e3-4ede-a8d1-6ede59d24921%2F6161%2F52F8%2F7F2C%2F2C42%2F6FC0%2F0A48%2F356B%2FBFA3%2Fhermes-paris.jpg&shop=57b2465e-10e3-4ede-a8d1-6ede59d24921", reference: "Hermès" },
    { prompt: "Quel est cette marque ?", image: "https://www.numerama.com/content/uploads/2016/06/13502130_10153696123838870_522765110773053650_n-796x796-2.png", reference: "Netflix" },
    { prompt: "Quel est cette marque ?", image: "https://cdn.worldvectorlogo.com/logos/michelin-2.svg", reference: "Michelin" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/3840px-Microsoft_logo.svg.png", reference: "Microsoft (pas Domino's pizza" },
    { prompt: "Quel est cette marque ?", image: "https://embroideres.com/files/cache/042a7c76b4c950dc1882acfc97f5cf25_f1000671.jpg", reference: "KFC" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2021/02/Logo-Tesla.jpg", reference: "Tesla" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2020/04/Chanel-Symbole.jpg", reference: "Chanel" },
    { prompt: "Quel est cette marque ?", image: "https://assets.turbologo.com/blog/en/2021/07/07075142/PlayStation-logo-1994.png", reference: "Playstation" },
    { prompt: "Quel est cette marque ?", image: "https://www.art-deco-stickers.fr/16913/sticker-autocollant-logo-embleme-yamaha.jpg", reference: "Yamaha" },
    { prompt: "A quel entreprise appartient ce logo ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3XBDKzvzGd7H0d9OhJwi5tBiZhUybpbT3xWcfhgzy4w&s=10", reference: "Warner Bros" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e8/Shell_logo.svg/3840px-Shell_logo.svg.png", reference: "Shell" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIBhgjk1R4SaJKM1qdv7SHJTwW5i1uK8OfOvhjkyfdX8cCWRd3oYeku_jW&s=10", reference: "WWF" },
    { prompt: "Quel est cette marque ?", image: "https://play-lh.googleusercontent.com/-sfpej5glWUgJjbt7kPKC3ChTyWIeKPGPA7CyrqYlCZWd16sxCYlZBU1x1ohmMd_IVQwk3CCfByOSw1EnFRc=w600-h300-pc0xffffff-pd", reference: "Crousty one" },
  ],
 
  /* ================= CULTURE GÉNÉRALE ================= */
  culture_generale: [
    { prompt: "Combien de continents compte-t-on généralement ?", reference: "5" },
    { prompt: "Quelle est la monnaie utilisée au Japon ?", reference: "Le yen" },
    { prompt: "Quel est le plus grand océan du monde ?", reference: "L'océan Pacifique" },
    { prompt: "Combien de couleurs compte l'arc-en-ciel traditionnellement ?", reference: "7" },
    { prompt: "Quelle est la langue la plus parlée au monde (à échelles de locuteurs natifs) ?", reference: "Le mandarin" },
    { prompt: "Quel est le symbole chimique de l'eau ?", reference: "H2O" },
    { prompt: "Combien de jours compte une année bissextile ?", reference: "366" },
    { prompt: "Quel pays a la forme d'une botte sur la carte d'Europe ?", reference: "L'Italie" },
    { prompt: "Quel est l'instrument de musique à 88 touches ?", reference: "Le piano" },
    { prompt: "Quelle planète est surnommée la « planète rouge » ?", reference: "Mars" },
    { prompt: "Combien de temps la Lune met-elle environ à tourner autour de la Terre ?", reference: "Environ 27 à 29 jours" },
    { prompt: "Quel est le plus long fleuve de France ?", reference: "La Loire" },
    { prompt: "Quel sport se joue à Wimbledon ?", reference: "Le tennis" },
    { prompt: "Combien de cordes compte une guitare classique ?", reference: "6" },
    { prompt: "Quelle est la capitale de l'Italie ?", reference: "Rome" },
    { prompt: "Quel est l'animal terrestre le plus rapide du monde ?", reference: "Le guépard" },
    { prompt: "Combien de faces possède un dé classique ?", reference: "6" },
    { prompt: "Quel gaz respirons-nous principalement pour vivre ?", reference: "L'oxygène" },
    { prompt: "Quelle est la capitale de l'Espagne ?", reference: "Madrid" },
    { prompt: "Combien de temps dure une olympiade ?", reference: "4 ans" },
    { prompt: "Quel est le plus petit os du corps humain ?", reference: "L'étrier (dans l'oreille)" },
    { prompt: "Quelle est la capitale du Japon ?", reference: "Tokyo" },
    { prompt: "Quel fruit est associé à Isaac Newton et la découverte de la gravité ?", reference: "La pomme" },
    { prompt: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", reference: "Environ 8 minutes" },
    { prompt: "Quelle est la capitale de l'Allemagne ?", reference: "Berlin" },
    { prompt: "Quel est le nom du satellite naturel de la Terre ?", reference: "La Lune" },
    { prompt: "Combien de pattes a une araignée ?", reference: "8" },
    { prompt: "Quelle est la plus grande île du monde ?", reference: "Le Groenland" },
    { prompt: "Quel métal est symbolisé par « Au » ?", reference: "L'or" },
    { prompt: "Quel pays a inventé le sushi ?", reference: "Le Japon" },
    { prompt: "Quelle est la vitesse du son approximativement dans l'air ?", reference: "Environ 340 mètres par seconde" },
    { prompt: "Quel organe humain filtre le sang pour produire l'urine ?", reference: "Le rein" },
    { prompt: "Quelle est la capitale du Portugal ?", reference: "Lisbonne" },
    { prompt: "Combien de dents a un adulte en moyenne ?", reference: "32" },
    { prompt: "Quel est le plus grand désert froid du monde ?", reference: "L'Antarctique" },
    { prompt: "Quelle est la monnaie utilisée au Royaume-Uni ?", reference: "La livre sterling" },
    { prompt: "Quel est l'organe principal du système nerveux ?", reference: "Le cerveau" },
    { prompt: "Combien de zéros comporte un million écrit en chiffres ?", reference: "6" },
    { prompt: "Quelle est la capitale de la Russie ?", reference: "Moscou" },
    { prompt: "Quel animal est le meilleur ami de l'homme, selon l'expression ?", reference: "Le chien" },
    { prompt: "Quel est le plus haut sommet d'Europe ?", reference: "Le mont Elbrouz (ou le Mont Blanc pour l'Europe de l'Ouest)" },
    { prompt: "Combien de continents la Russie chevauche-t-elle ?", reference: "2 (Europe et Asie)" },
    { prompt: "Quel est le plus grand pays d'Afrique par la population ?", reference: "Le Nigeria" },
    { prompt: "Quelle est la capitale des États-Unis ?", reference: "Washington D.C." },
    { prompt: "Quel est le symbole chimique du sel de table ?", reference: "NaCl" },
    { prompt: "Quelle est la couleur obtenue en mélangeant le bleu et le jaune ?", reference: "Le vert" },
    { prompt: "Quel est le plus grand mammifère marin ?", reference: "La baleine bleue" },
    { prompt: "Combien de minutes dure un match de basketball NBA hors prolongations ?", reference: "48 minutes" },
    { prompt: "Quel est le nom de la galaxie qui contient notre système solaire ?", reference: "La Voie lactée" },
    { prompt: "Quelle est la capitale de la Chine ?", reference: "Pékin" },
    { prompt: "Quelle est la capitale de l'Australie ?", reference: "Canberra (et non Sydney)" },
    { prompt: "Quel est le plus long fleuve du monde ?", reference: "Le Nil (ou l'Amazone)" },
    { prompt: "Quelle montagne est le point culminant de la planète ?", reference: "Le mont Everest" },
    { prompt: "Quelle unité mesure l'intensité du courant électrique ?", reference: "L'ampère" },
    { prompt: "Combien y a-t-il d'os dans le corps humain adulte ?", reference: "206" },
    { prompt: "Quelle est la plus grande planète du système solaire ?", reference: "Jupiter" },
    { prompt: "Combien de joueurs y a-t-il dans une équipe de football (sur le terrain) ?", reference: "11" },
    { prompt: "Quel océan borde la côte ouest des États-Unis ?", reference: "L'océan Pacifique" },
    { prompt: "Qui a peint le plafond de la chapelle Sixtine ?", reference: "Michel-Ange" },
    { prompt: "Quel est le symbole chimique du fer ?", reference: "Fe" },
    { prompt: "Dans quel pays se trouve la ville de Dubaï ?", reference: "Les Émirats arabes unis" },
    { prompt: "Comment appelle-t-on un triangle qui a trois côtés de même longueur ?", reference: "Un triangle équilatéral" },
    { prompt: "Quelle est la capitale de la Suisse ?", reference: "Berne" },
    { prompt: "Quel est le gaz le plus abondant dans l'atmosphère terrestre ?", reference: "L'azote" },
    { prompt: "Qui est le créateur des personnages de Mickey Mouse et Donald Duck ?", reference: "Walt Disney" },
    { prompt: "Dans quel sport s'illustre Rafael Nadal ?", reference: "Le tennis" },
    { prompt: "Quelle mer borde le sud de la France ?", reference: "La mer Méditerranée" },
    { prompt: "En informatique, que signifie l'abréviation 'URL' ?", reference: "Uniform Resource Locator (ou l'adresse web)" },
    { prompt: "Combien de lettres contient l'alphabet français ?", reference: "26" },
    { prompt: "Quelle couleur obtient-on en mélangeant du rouge et du blanc ?", reference: "Du rose" },
    { prompt: "Quel est le plus grand État des États-Unis en superficie ?", reference: "L'Alaska" },
    { prompt: "Quel fruit produit le vin ?", reference: "Le raisin" },
    { prompt: "Combien font 7 multiplié par 8 ?", reference: "56" },
    { prompt: "Dans quelle ville peut-on visiter le Colisée ?", reference: "Rome" },
    { prompt: "Quel arbre produit des glands ?", reference: "Le chêne" },
  ],
film: [
    { prompt: "Devine le film avec ces indices : 🚢🧊🚪🎻", reference: "Titanic" },
    { prompt: "Devine le film avec ces indices : 🧙‍♂️⚡👓🦉", reference: "Harry Potter" },
    { prompt: "Devine le film avec ces indices : 🏴‍☠️🦜🚢⚔️", reference: "Pirates des Caraïbes" },
    { prompt: "Devine le film avec ces indices : 💊🕶️🐇💻", reference: "Matrix" },
    { prompt: "Devine le film avec ces indices : 🦖🦕🚙🌋", reference: "Jurassic Park" },
    { prompt: "Devine le film avec ces indices : 👽🚲🌕🌌", reference: "E.T. l'extra-terrestre" },
    { prompt: "Devine le film avec ces indices : 🦁👑🐗🐛", reference: "Le Roi Lion" },
    { prompt: "Devine le film avec ces indices : 🕷️🕸️🏙️🦸‍♂️", reference: "Spider-Man" },
    { prompt: "Devine le film avec ces indices : 🗡️💍🌋🧝‍♂️", reference: "Le Seigneur des Anneaux" },
    { prompt: "Devine le film avec ces indices : 🚗🕰️⚡🔥", reference: "Retour vers le futur" },
    { prompt: "Devine le film avec ces indices : ⛄❄️👸🦌", reference: "La Reine des Neiges" },
    { prompt: "Devine le film avec ces indices : 🦍🏢🚁👱‍♀️", reference: "King Kong" },
    { prompt: "Devine le film avec ces indices : 🍫🏭🎩👴", reference: "Charlie et la Chocolaterrie" },
    { prompt: "Devine le film avec ces indices : 🧸🤠🚀🌌", reference: "Toy Story" },
    { prompt: "Devine le film avec ces indices : 🐟🐠👨‍👦🌊", reference: "Le Monde de Nemo" },
    { prompt: "Devine le film avec ces indices : 🦇🚙🔦🌃", reference: "Batman" },
    { prompt: "Devine le film avec ces indices : 🥋🐼🍜🎋", reference: "Kung Fu Panda" },
    { prompt: "Devine le film avec ces indices : 🐍🤠🕵️‍♂️🗿", reference: "Indiana Jones" },
    { prompt: "Devine le film avec ces indices : 🥊🥩🏃‍♂️🎶", reference: "Rocky" },
    { prompt: "Devine le film avec ces indices : 🧜‍♀️🦀🐠🎶", reference: "La Petite Sirène" },
    { prompt: "Devine le film avec ces indices : 🤖🕶️🏍️👍", reference: "Terminator" },
    { prompt: "Devine le film avec ces indices : 🎈🏠👴👦", reference: "Là-Haut" },
    { prompt: "Devine le film avec ces indices : 🐧🧊💃🎶", reference: "Happy Feet" },
    { prompt: "Devine le film avec ces indices : 🎭🌹👹🏰", reference: "La Belle et la Bête" },
    { prompt: "Devine le film avec ces indices : 👻🚫🔫🟢", reference: "S.O.S Fantômes" },
    { prompt: "Devine le film avec ces indices : 🟢👹🫏🏰", reference: "Shrek" },
    { prompt: "Devine le film avec ces indices : 🌀🛌👔⏳", reference: "Inception" },
    { prompt: "Devine le film avec ces indices : 🦈🌊🚤🩸", reference: "Les Dents de la mer" },
    { prompt: "Devine le film avec ces indices : 👽📞🚲🌕", reference: "E.T. l'extra-terrestre" },
    { prompt: "Devine le film avec ces indices : 🐀👨‍🍳🍲🇫🇷", reference: "Ratatouille" },
    { prompt: "Devine le film avec ces indices : 🏴‍☠️🪝🐊🧚‍♀️", reference: "Peter Pan" },
    { prompt: "Devine le film avec ces indices : 🦁🧙‍♀️👗🚪", reference: "Le Monde de Narnia" },
    { prompt: "Devine le film avec ces indices : 👦🐒🌴🐅", reference: "Le Livre de la Jungle" },
    { prompt: "Devine le film avec ces indices : 🚗🏁⚡🏆", reference: "Cars" },
    { prompt: "Devine le film avec ces indices : 👴🚙👴🏻⚡", reference: "Gran Torino" }, // Varions pour du tout public :
    { prompt: "Devine le film avec ces indices : 🕵️‍♂️🇬🇧🍸🔫", reference: "James Bond (007)" },
    { prompt: "Devine le film avec ces indices : 👨‍🚀🌌🕳️⏳", reference: "Interstellar" },
    { prompt: "Devine le film avec ces indices : 👽🔫🕶️🐶", reference: "Men in Black" },
    { prompt: "Devine le film avec ces indices : 🦁🦓🦒🦛", reference: "Madagascar" },
    { prompt: "Devine le film avec ces indices : 🧛‍♂️🐺👧🌲", reference: "Twilight" },
    { prompt: "Devine le film avec ces indices : 🗡️🛡️🏟️🐯", reference: "Gladiator" },
    { prompt: "Devine le film avec ces indices : 🎈🤡🛶🌧️", reference: "Ça (It)" },
    { prompt: "Devine le film avec ces indices : 🎸💀🌼🇲🇽", reference: "Coco" },
    { prompt: "Devine le film avec ces indices : 🚀🌌⚔️🤖", reference: "Star Wars" },
    { prompt: "Devine le film avec ces indices : 🦊🐰🚔🥕", reference: "Zootopie" },
    { prompt: "Devine le film avec ces indices : 🧞‍♂️🐒🕌✨", reference: "Aladdin" },
    { prompt: "Devine le film avec ces indices : 👧🐉👹🛁", reference: "Le Voyage de Chihiro" },
  ],
 
  series: [
    { prompt: "Devine la série avec ces indices : 🐉❄️🐺👑", reference: "Game of Thrones" },
    { prompt: "Devine la série avec ces indices : 🚲🧇👽🔦", reference: "Stranger Things" },
    { prompt: "Devine la série avec ces indices : 🧪⚗️🚐💰", reference: "Breaking Bad" },
    { prompt: "Devine la série avec ces indices : 🧟‍♂️🏹🏏🏚️", reference: "The Walking Dead" },
    { prompt: "Devine la série avec ces indices : 🏦🎭🔴💸", reference: "La Casa de Papel" },
    { prompt: "Devine la série avec ces indices : 👨‍⚕️🦯💊🏥", reference: "Dr House" },
    { prompt: "Devine la série avec ces indices : 🛋️☕🏢👫", reference: "Friends" },
    { prompt: "Devine la série avec ces indices : 🛡️⚔️🛶🥶", reference: "Vikings" },
    { prompt: "Devine la série avec ces indices : 🕵️‍♂️🇬🇧🎻🧠", reference: "Sherlock" },
    { prompt: "Devine la série avec ces indices : 🦇👨‍✈️🚔🌃", reference: "Gotham" },
    { prompt: "Devine la série avec ces indices : 👑🇬🇧👗☕", reference: "The Crown" },
    { prompt: "Devine la série avec ces indices : 👨‍👨‍👦‍👦💻🤓🏢", reference: "Silicon Valley" },
    { prompt: "Devine la série avec ces indices : 🩸🧛‍♂️🇺🇸🏫", reference: "Vampire Diaries" },
    { prompt: "Devine la série avec ces indices : 🚔🚨🕵️‍♂️🏙️", reference: "Brooklyn Nine-Nine" },
    { prompt: "Devine la série avec ces indices : 👦🧠🦸‍♂️⚡", reference: "The Flash" },
    { prompt: "Devine la série avec ces indices : 👨‍👩‍👧‍👦🍩🍺📺", reference: "Les Simpson" },
    { prompt: "Devine la série avec ces indices : 👨‍💼📉🖨️🏢", reference: "The Office" },
    { prompt: "Devine la série avec ces indices : 🦸‍♂️🇺🇸🛡️🦅", reference: "The Boys" },
    { prompt: "Devine la série avec ces indices : 🪞💻📱😨", reference: "Black Mirror" },
    { prompt: "Devine la série avec ces indices : 🏥👩‍⚕️🩺💔", reference: "Grey's Anatomy" },
    { prompt: "Devine la série avec ces indices : 😈👮‍♂️🍸🏢", reference: "Lucifer" },
    { prompt: "Devine la série avec ces indices : 🧙‍♀️🐈‍⬛🔮🧹", reference: "Sabrina l'apprentie sorcière" },
    { prompt: "Devine la série avec ces indices : 🔫👔🐎🎩", reference: "Peaky Blinders" },
    { prompt: "Devine la série avec ces indices : 🧑‍🦲👊💥🦸‍♂️", reference: "One Punch Man" },
    { prompt: "Devine la série avec ces indices : 🧑‍🚀🌌🛸⚔️", reference: "The Mandalorian" },
    { prompt: "Devine la série avec ces indices : 🦑🔴🟢💰", reference: "Squid Game" },
    { prompt: "Devine la série avec ces indices : 🐺⚔️🪙🛁", reference: "The Witcher" },
    { prompt: "Devine la série avec ces indices : ⛓️🏢🏃‍♂️🗺️", reference: "Prison Break" },
    { prompt: "Devine la série avec ces indices : 🩸🔪🛥️👨‍🔬", reference: "Dexter" },
    { prompt: "Devine la série avec ces indices : 🧑‍✈️✈️🏝️🔢", reference: "Lost : Les Disparus" },
    { prompt: "Devine la série avec ces indices : 👩‍⚖️🔪⚖️🩸", reference: "How to Get Away with Murder" },
    { prompt: "Devine la série avec ces indices : 🚗👻👿👼", reference: "Supernatural" },
    { prompt: "Devine la série avec ces indices : 👩‍🦰♟️🥃💊", reference: "Le Jeu de la Dame (The Queen's Gambit)" },
    { prompt: "Devine la série avec ces indices : 👑🏰🐉🔥", reference: "House of the Dragon" },
    { prompt: "Devine la série avec ces indices : 👩‍⚕️1945🏴󠁧󠁢󠁳󠁣󠁴󠁿🕰️", reference: "Outlander" },
    { prompt: "Devine la série avec ces indices : 👽🛸🔎👽", reference: "X-Files" },
    { prompt: "Devine la série avec ces indices : 🧟‍♂️🌿🍄👧", reference: "The Last of Us" },
    { prompt: "Devine la série avec ces indices : 👨‍👩‍👧‍👦🕰️☂️🦸‍♂️", reference: "Umbrella Academy" },
    { prompt: "Devine la série avec ces indices : 🛹🚸👯‍♀️💅", reference: "Euphoria" },
    { prompt: "Devine la série avec ces indices : 👔💼🏢🥃", reference: "Mad Men" },
    { prompt: "Devine la série avec ces indices : 🧟‍♀️🩸🏫🇰🇷", reference: "All of Us Are Dead" },
    { prompt: "Devine la série avec ces indices : 🤠🤖🏜️🎠", reference: "Westworld" },
    { prompt: "Devine la série avec ces indices : 🥷🥋🐍👊", reference: "Cobra Kai" },
    { prompt: "Devine la série avec ces indices : 🎩🇬🇧🍷🏰", reference: "Downton Abbey" },
    { prompt: "Devine la série avec ces indices : 👩‍💻🇫🇷🕵️‍♂️📞", reference: "Le Bureau des Légendes" },
    { prompt: "Devine la série avec ces indices : 📺💼🎬🌅", reference: "BoJack Horseman" },
    { prompt: "Devine la série avec ces indices : ⚔️🛡️🦅👑", reference: "Le Seigneur des Anneaux : Les Anneaux de Pouvoir" },
    { prompt: "Devine la série avec ces indices : 👨‍🍳🔪🥩🍔", reference: "The Bear" },
    { prompt: "Devine la série avec ces indices : 🦸‍♂️🦹‍♂️⚖️😈", reference: "Daredevil" },
  ],
 
  musique: [
    { prompt: "Complète les paroles : 'Allons enfants de la Patrie, Le jour de gloire est...'", reference: "Arrivé" },
    { prompt: "De quelle chanson viennent ces paroles : 'Is this the real life? Is this just fantasy?'", reference: "Bohemian Rhapsody (Queen)" },
    { prompt: "Complète les paroles (Stromae) : 'Où t'es, papa...'", reference: "Où t'es" },
    { prompt: "De quelle chanson viennent ces paroles : 'Je t'aime, à la folie, comme un fou, comme un soldat...'", reference: "Je t'aime (Lara Fabian)" },
    { prompt: "Complète les paroles : 'Sous les sunlight des tropiques, l'amour se raconte en...'", reference: "Musique" },
    { prompt: "Complète les paroles (Céline Dion) : 'Near, far, wherever you...'", reference: "Are" },
    { prompt: "De quelle chanson viennent ces paroles : 'I'm a survivor, I'm not gonna give up'", reference: "Survivor (Destiny's Child)" },
    { prompt: "Complète les paroles : 'Emmenez-moi au bout de la...'", reference: "Terre (Charles Aznavour)" },
    { prompt: "De quelle chanson viennent ces paroles : 'Billie Jean is not my lover'", reference: "Billie Jean (Michael Jackson)" },
    { prompt: "Complète les paroles : 'Et tu chantes, chantes, chantes ce refrain qui te...'", reference: "Plaît (Début de soirée)" },
    { prompt: "De quelle chanson viennent ces paroles : 'Wake me up before you go-go'", reference: "Wake Me Up Before You Go-Go (Wham!)" },
    { prompt: "Complète les paroles : 'Baby Baby, j'veux faire...'", reference: "Ma vie Avec toi. (A&M)" },
    { prompt: "De quelle chanson viennent ces paroles : 'I will always love you'", reference: "I Will Always Love You (Whitney Houston)" },
    { prompt: "Complète les paroles (Ed Sheeran) : 'I'm in love with the shape of...'", reference: "You" },
    { prompt: "Complète les paroles : 'Laissez-moi danser, laissez-moi, laissez-moi...'", reference: "Danser (Dalida)" },
    { prompt: "De quelle chanson viennent ces paroles : 'Hello from the other side'", reference: "Hello (Adele)" },
    { prompt: "Complète les paroles : 'Il jouait du piano...'", reference: "Debout (France Gall)" },
    { prompt: "De quelle chanson viennent ces paroles : 'On m'a dit que la monnaie c'était comme un Médicament''", reference: "Medicament - Anyme & Houdi" },
    { prompt: "Complète les paroles : 'Les démons de minuit, m'entraînent jusqu'a...'", reference: "L'insomnie (Images)" },
    { prompt: "De quelle chanson viennent ces paroles : 'Oops!... I Did It Again'", reference: "Oops!... I Did It Again (Britney Spears)" },
    { prompt: "Complète les paroles : 'Voyage, voyage, plus loin que la...'", reference: "Nuit et le jour (Desireless)" },
    { prompt: "De quelle chanson viennent ces paroles : 'We are the champions, my friends'", reference: "We Are the Champions (Queen)" },
    { prompt: "Complète les paroles : 'La bohème, la bohème, ça voulait dire on est...'", reference: "Heureux (Charles Aznavour)" },
    { prompt: "De quelle chanson viennent ces paroles : 'They tried to make me go to rehab, but I said, No, no, no'", reference: "Rehab (Amy Winehouse)" },
    { prompt: "Complète les paroles : 'Ne la laisse pas tomber, elle est si...'", reference: "Fragile" },
     { prompt: "Complète les paroles (Édith Piaf) : 'Non, rien de rien, non, je ne regrette...'", reference: "Rien" },
    { prompt: "De quelle chanson viennent ces paroles : 'Il est cinq heures, Paris s'éveille...'", reference: "Il est cinq heures, Paris s'éveille (Jacques Dutronc)" },
    { prompt: "Complète les paroles (Johnny Hallyday) : 'Qu'on me donne l'obscurité, puis la lumière, qu'on me donne...'", reference: "L'envie" },
    { prompt: "De quelle chanson viennent ces paroles : 'You're the one that I want, (you are the one I want), ooh, ooh, ooh...'", reference: "You're the One That I Want (Grease)" },
    { prompt: "Complète les paroles (Jean-Jacques Goldman) : 'Quand la musique est...'", reference: "Bonne" },
    { prompt: "De quelle chanson viennent ces paroles : 'Around the world, around the world...'", reference: "Around the world (Daft Punk)" },
    { prompt: "Complète les paroles (Renaud) : 'Dès que le vent soufflera, je repartira...'", reference: "Dès que les vents tourneront" },
    { prompt: "De quelle chanson viennent ces paroles : 'Mamma mia, here I go again...'", reference: "Mamma Mia (ABBA)" },
    { prompt: "Complète les paroles (Orelsan) : 'Si c'est trop souvent la même chose, c'est que c'est...'", reference: "Basique" },
    { prompt: "De quelle chanson viennent ces paroles : 'Every breath you take, every move you make...'", reference: "Every Breath You Take (The Police)" },
    { prompt: "Complète les paroles (Céline Dion) : 'S'il suffisait qu'on s'aime, s'il suffisait...'", reference: "D'aimer" },
    { prompt: "De quelle chanson viennent ces paroles : 'Smells like teen spirit...'", reference: "Smells Like Teen Spirit (Nirvana)" },
    { prompt: "Complète les paroles (Aya Nakamura) : 'Oh Djadja, y'a pas moyen...'", reference: "Djadja" },
    { prompt: "De quelle chanson viennent ces paroles : 'I can't get no, satisfaction...'", reference: "(I Can't Get No) Satisfaction (The Rolling Stones)" },
    { prompt: "Complète les paroles (Indochine) : 'J'ai demandé à la lune, et le soleil ne le sait...'", reference: "Pas" },
    { prompt: "De quelle chanson viennent ces paroles : 'Hotel California, such a lovely place...'", reference: "Hotel California (Eagles)" },
    { prompt: "Complète les paroles (Michel Sardou) : 'Ne m'appelez plus jamais France, la France elle m'a laissé...'", reference: "Tomber" },
    { prompt: "De quelle chanson viennent ces paroles : 'Sweet child o' mine...'", reference: "Sweet Child O' Mine (Guns N' Roses)" },
    { prompt: "Complète les paroles (Julien Doré) : 'Paris, Seychelles, je te...'", reference: "Cherche" },
    { prompt: "De quelle chanson viennent ces paroles : 'Girls just want to have fun...'", reference: "Girls Just Want to Have Fun (Cyndi Lauper)" },
    { prompt: "Complète les paroles (Vianney) : 'T'es où ? Pas là, mais t'es pas...'", reference: "Là" },
    { prompt: "De quelle chanson viennent ces paroles : 'Hit me baby one more time...'", reference: "...Baby One More Time (Britney Spears)" },
    { prompt: "Complète les paroles (Kyo) : 'On a parcouru le chemin, on a tenu la...'", reference: "Distance (Le Chemin)" },
    { prompt: "De quelle chanson viennent ces paroles : 'Like a virgin, touched for the very first time...'", reference: "Like a Virgin (Madonna)" },
    { prompt: "Complète les paroles (Angèle) : 'Tout oublier, pour tout...'", reference: "Recommencer" }
  ]
};
 
const CATEGORY_LABELS = {
  animaux: "Animaux",
  drapeaux: "Drapeaux",
  histoire: "Histoire",
  grandes_figures: "Grandes figures & événements",
  francais: "Français",
  marques: "Marques (indices)",
  culture_generale: "Culture générale",
  film: "Films (emojis)",
  series: "Séries (emojis)",
  musique: "Musique (Paroles)"
};
 
if (typeof module !== 'undefined') { module.exports = QUESTION_BANK; }
if (typeof window !== 'undefined') { window.QUESTION_BANK = QUESTION_BANK; window.CATEGORY_LABELS = CATEGORY_LABELS; }
