/* ============================================================
   A&M QUIZZ — BANQUE DE QUESTIONS
   ------------------------------------------------------------
   Chaque question a la forme :
   { category, type, prompt, image (optionnel), reference (optionnel) }

   - "reference" = la réponse attendue, affichée à l'hôte ET à tous
     les joueurs pendant la phase de correction (sauf pour le petit
     bac, où "reference" contient juste des EXEMPLES pour aider
     l'hôte à juger, pas LA réponse).
   - L'hôte valide chaque réponse joueur par Vrai/Faux, quelle que
     soit la catégorie : c'est un choix demandé explicitement (jeu
     entre amis, pas de correction automatique rigide).

   POUR AJOUTER DES QUESTIONS : copie une ligne existante de la
   catégorie voulue et remplace le contenu. Aucune limite de taille.
   ============================================================ */

const QUESTION_BANK = {

  /* ================= ANIMAUX (à deviner) ================= */
  animaux: [
    { prompt: "Quel est cet animal ?", image: "https://cdn-images.zoobeauval.com/pTsc7axkqY3t5MzSk0WS5C3K7Ig=/730x730/https%3A%2F%2Fs3.eu-west-3.amazonaws.com%2Fimages.zoobeauval.com%2F2024%2F02%2Fgirafe-02-65ccbbb1cfc0b.jpg", reference: "Girafe" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Lion_d%27Afrique.jpg", reference: "Lion" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/3/37/African_Bush_Elephant.jpg", reference: "Éléphant" },
    { prompt: "Quel est cet animal ?", image: "https://www.zoodejurques.fr/wp-content/uploads/2019/05/Jillian-Knox_Grevys-Zebra_305-fullsizeoutput_ce1d-1000x1000-c-center.jpg", reference: "Zèbre" },
    { prompt: "Quel est cet animal ?", image: "https://wildexpedition.com/wp-content/uploads/2024/09/DSCN7042.jpeg", reference: "Hippopotame" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Nile_crocodile_head.jpg", reference: "Crocodile" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21606/hibou-des-marais-1068x1200.jpg", reference: "Hibou" },
    { prompt: "Quel est cet animal ?", image: "https://zooecomuseum.ca/workspace/uploads/modules/pygargue-mobile-fr-1575566403.jpg", reference: "Aigle" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Madagascan_Flying_Fox_%28Pteropus_rufus%29_%28captive_specimen%29_%289674779460%29.jpg/330px-Madagascan_Flying_Fox_%28Pteropus_rufus%29_%28captive_specimen%29_%289674779460%29.jpg", reference: "Chauve-souris" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGLW5dQukkIUiH5DvPv9DiiSMdS8iR2h3h44F8aFYFW736HcndXKmfXgfx&s=10", reference: "Dauphin" },
    { prompt: "Quel est cet animal ?", image: "https://static.ocean.org/oceanorg/2026/02/Humpback-whale-shutterstock_1455196766-1005x670-1.jpg", reference: "Baleine" },
    { prompt: "Quel est cet animal ?", image: "https://animauxmarins.fr/wp-content/uploads/2023/06/grand-requin-marteau.jpg", reference: "Requin Marteau" },
    { prompt: "Quel est cet animal ?", image: "https://cdn-images.zoobeauval.com/lTt4TMwFmYnHjH6mYkbwBuFAD4U=/730x730/https%3A%2F%2Fs3.eu-west-3.amazonaws.com%2Fimages.zoobeauval.com%2F2025%2F07%2Ftortue-aldabra-01-687e0770c8cc1.jpg", reference: "Tortue" },
    { prompt: "Quel est cet animal ?", image: "https://www.navetteaixmarseille.com/wp-content/uploads/elementor/thumbs/herisson-r1dams0o70yrgejw8xbluxox6008kqnjd07qt7lgts.jpg", reference: "Hérisson" },
    { prompt: "Quel est cet animal ?", image: "https://wwf.ca/wp-content/uploads/2024/11/Original_WW1287619-1024x679.jpg", reference: "Loutre" },
    { prompt: "Quel est cet animal ?", image: "https://www.sciencesetavenir.fr/assets/img/2014/09/26/cover-r4x3w1200-57e153aea71a2-le-paresseux.jpg", reference: "Paresseux" },
    { prompt: "Quel est cet animal ?", image: "https://media.ouest-france.fr/v1/pictures/120627b1b5ce29c8281dab952a8b982c-8490513.jpg?width=1260&client_id=eds&sign=74ac0093649c2e9e018e33fff7c1aae13d43304fea0fd1a9e1991ec2238f180c", reference: "Kangourou" },
    { prompt: "Quel est cet animal ?", image: "https://cdn.britannica.com/26/162626-050-3534626F/Koala.jpg", reference: "Koala" },
    { prompt: "Quel est cet animal ?", image: "https://static.europe1.fr/var/europe1/storage/styles/image_750_422/public/media/image/2025/02/15/11/le-panda-geant-n-est-plus-en-danger-mais-reste-menace.jpg?itok=yGQuBPtR", reference: "Panda" },
    { prompt: "Quel est cet animal ?", image: "https://www.phiessences.com/images/product_images/original_images/dreamstime-Lama_754pixel.jpg", reference: "Lama" },
    { prompt: "Quel est cet animal ?", image: "https://www.snpn.com/wp-content/uploads/2022/12/photo_snpn_Cervus-elaphus-hor.png-1200x1200.jpg", reference: "Cerf Élaphe" },
    { prompt: "Quel est cet animal ?", image: "https://zoodyssee.fr/wp-content/uploads/2026/02/sanglier_interieur2.webp", reference: "Sanglier" },
    { prompt: "Quel est cet animal ?", image: "https://www.zoologiste.com/images/main/blaireau.jpg", reference: "Blaireau" },
    { prompt: "Quel est cet animal ?", image: "https://www.lechasseurfrancais.com/wp-content/uploads/2025/04/le-castor-deurope-fait-son-grand-retour-en-alsace.jpg", reference: "Castor" },
    { prompt: "Quel est cet animal ?", image: "https://www.autourdesanimaux.com/wp-content/uploads/races/2465/lg_flamant-rose_646dcc2908f77.webp?1", reference: "Flamant rose" },
    { prompt: "Quel est cet animal ?", image: "https://blooming-pets.com/wp-content/uploads/2025/09/Paon-Bleu-Pavo-Cristatus.png.webp", reference: "Paon" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ6tmwiVcLklUa_EKQUOdjXMh4ZxhRYKpfbCj-6S21bXXefmwPJrPA6MI&s=10", reference: "Perroquet" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Manchot_empereur.jpg", reference: "Manchot" },
    { prompt: "Quel est cet animal ?", image: "https://www.aquariumbiarritz.com/wp-content/uploads/2025/06/phoque-gris-aquarium-de-biarritz-delphine-pernaud-8-614x1024.jpg", reference: "Phoque" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21601/anatomie-externe-de-lescargot-848x514.jpg", reference: "Escargot" },
    { prompt: "Quel est cet animal ?", image: "https://cdn.prod.website-files.com/62321a3fcb1f1e70c916da25/64a300d0572f25f2be24798b_papillon-monarque-emergence20-topweb.jpg", reference: "Papillon" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/21612/dessin-dabeille-domestique-848x836.jpg", reference: "Abeille" },
    { prompt: "Quel est cet animal ?", image: "https://primary.jwwb.nl/public/o/j/v/temp-hzihylvryzejjaqjmgne/img_20240712_163544-high.jpg?enable-io=true&enable=upscale&fit=bounds&width=1200", reference: "Araignée" },
    { prompt: "Quel est cet animal ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWV7pyzVfr8_6gK3ArhtXGvBVbXDqORYDIAV-Q9K5cLOgzN9Hes_HtAtuo&s=10", reference: "Scorpion" },
    { prompt: "Quel est cet animal ?", image: "https://master.salamandre.org/media/22505/AdobeStock_95634179-1800x1200.jpeg", reference: "Poulpe" },
    { prompt: "Quel est cet animal ?", image: "https://www.tastefrance.com/sites/default/files/2020-11/Calmar.jpg", reference: "Calamar" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/KreeftbijDenOsse.jpg", reference: "Homard" },
    { prompt: "Quel est cet animal ?", image: "https://www.oceanopolis.com/wp-content/uploads/2019/11/crabe-dormeur-cancer-pagurus-oceanopolis-800x533.jpg", reference: "Crabe" },
    { prompt: "Quel est cet animal ?", image: "https://image.jimcdn.com/app/cms/image/transf/dimension=420x10000:format=png/path/s5dde8bff85c81b2f/image/i27a521a2e37eecca/version/1642492557/chameau-image-animaux-transparent-sur-fond-blanc-pour-site-web-illustration-ecole-montessori.png", reference: "Chameau" },
    { prompt: "Quel est cet animal ?", image: "https://media.ooreka.fr/public/image/dinde-basse-cour-ferme-main-11910359.jpg", reference: "Dinde" },
    { prompt: "Quel est cet animal ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Red_Squirrel_-_Lazienki.JPG/330px-Red_Squirrel_-_Lazienki.JPG", reference: "Écureuil" },
    { prompt: "Quel animal est surnommé le « roi de la savane » ?", reference: "Le lion" },
    { prompt: "Quel est le plus grand animal terrestre actuel ?", reference: "L'éléphant d'Afrique" },
    { prompt: "Quel est le plus grand animal du monde (marin ou terrestre) ?", reference: "La baleine bleue" },
    { prompt: "Quel oiseau ne sait pas voler mais court très vite en Afrique ?", reference: "L'autruche" },
    { prompt: "Quel animal change de couleur pour se camoufler ?", reference: "Le caméléon" },
  ],

  /* ================= PETIT BAC ================= */
  petit_bac: [
    { letter: "G", categories: ["Animal", "Célébrité", "Pays", "Prénom", "Métier", "Objet"],
      reference: { Animal: "Girafe", Célébrité: "Gyökeres", Pays: "Grèce", Prénom: "Gabriel", Métier: "Garagiste", Objet: "Gant" } },
    { letter: "M", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Marque"],
      reference: { Animal: "Mouton", Célébrité: "Messi", Ville: "Marseille", Prénom: "Marie", "Fruit/Légume": "Mangue", Marque: "Michelin" } },
    { letter: "P", categories: ["Animal", "Pays", "Prénom", "Métier", "Objet", "Sport"],
      reference: { Animal: "Panda", Pays: "Portugal", Prénom: "Paul", Métier: "Pompier", Objet: "Parapluie", Sport: "Pétanque" } },
    { letter: "C", categories: ["Animal", "Célébrité", "Ville", "Fruit/Légume", "Marque", "Métier"],
      reference: { Animal: "Chat", Célébrité: "Cristiano Ronaldo", Ville: "Cannes", "Fruit/Légume": "Citron", Marque: "Chanel", Métier: "Chirurgien" } },
    { letter: "L", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Lion", Pays: "Luxembourg", Prénom: "Léa", Objet: "Lampe", Sport: "Lutte", Marque: "Lacoste" } },
    { letter: "B", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Baleine", Célébrité: "Beyoncé", Ville: "Bordeaux", Prénom: "Benjamin", "Fruit/Légume": "Banane", Métier: "Boulanger" } },
    { letter: "R", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Renard", Pays: "Roumanie", Prénom: "Robert", Objet: "Radio", Sport: "Rugby", Marque: "Renault" } },
    { letter: "T", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Tigre", Célébrité: "Taylor Swift", Ville: "Toulouse", Prénom: "Thomas", "Fruit/Légume": "Tomate", Métier: "Traducteur" } },
    { letter: "S", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Serpent", Pays: "Suède", Prénom: "Sarah", Objet: "Stylo", Sport: "Ski", Marque: "Samsung" } },
    { letter: "A", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Aigle", Célébrité: "Adele", Ville: "Amiens", Prénom: "Alice", "Fruit/Légume": "Ananas", Métier: "Avocat" } },
    { letter: "D", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Dauphin", Pays: "Danemark", Prénom: "David", Objet: "Drapeau", Sport: "Danse", Marque: "Danone" } },
    { letter: "V", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Vache", Célébrité: "Vincent Cassel", Ville: "Valence", Prénom: "Victor", "Fruit/Légume": "Vigne (raisin)", Métier: "Vétérinaire" } },
    { letter: "N", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Nandou", Pays: "Norvège", Prénom: "Nicolas", Objet: "Nappe", Sport: "Natation", Marque: "Nike" } },
    { letter: "H", categories: ["Animal", "Célébrité", "Ville", "Prénom", "Fruit/Légume", "Métier"],
      reference: { Animal: "Hibou", Célébrité: "Hugh Jackman", Ville: "Honfleur", Prénom: "Hugo", "Fruit/Légume": "Haricot", Métier: "Horloger" } },
    { letter: "E", categories: ["Animal", "Pays", "Prénom", "Objet", "Sport", "Marque"],
      reference: { Animal: "Écureuil", Pays: "Espagne", Prénom: "Emma", Objet: "Écharpe", Sport: "Escrime", Marque: "Evian" } },
  ],

  /* ================= REBUS ================= */
  rebus: [
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/wRVyPtLF/Capture-d-ecran-2026-07-09-171518.png", reference: "Demain" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/JHqDgyZP/Capture-d-ecran-2026-07-09-171614.png", reference: "Univers" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/yWqmDcdz/Capture-d-ecran-2026-07-09-171629.png", reference: "Château" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/H82cKJX6/Capture-d-ecran-2026-07-09-171641.png", reference :"Souris" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/q6LhYtyZ/Capture-d-ecran-2026-07-09-171701.png", reference: "Tapis" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/V0RrTSnV/Capture-d-ecran-2026-07-09-171714.png", reference: "Chapeau" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/CdyGRk1w/Capture-d-ecran-2026-07-09-171730.png", reference: "Poubelle" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/sGcQ8B7q/Capture-d-ecran-2026-07-09-171743.png", reference: "Bureau" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/K3NkVKBd/Capture-d-ecran-2026-07-09-171756.png", reference: "Guitare" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/m1wzqc7f/Capture-d-ecran-2026-07-09-171811.png", reference: "Marteau" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/D4gJDW1V/Capture-d-ecran-2026-07-09-171830.png", reference: "Papillon" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/5Q3YGH8W/Capture-d-ecran-2026-07-09-171953.png", reference: "Blouse" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/hQrzwJVq/Capture-d-ecran-2026-07-09-172014.png", reference: "Salade" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/p5Zh79KP/Capture-d-ecran-2026-07-09-172027.png", reference: "Cravate" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/xNRJ7kL0/Capture-d-ecran-2026-07-09-172041.png", reference: "Ananas" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/Rqzgjjwq/Capture-d-ecran-2026-07-09-172110.png", reference: "Cheval" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/vDd0pp5T/Capture-d-ecran-2026-07-09-172122.png", reference: "Corbeau" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/CdVcWWbR/Capture-d-ecran-2026-07-09-172135.png", reference: "Panthère" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/xqS6WWLk/Capture-d-ecran-2026-07-09-172150.png", reference: "Grenouille" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/c6NFVVfn/Capture-d-ecran-2026-07-09-172204.png", reference: "Étoile" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/F1QT220J/Capture-d-ecran-2026-07-09-172218.png", reference: "Sapin" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/bdjmKK1k/Capture-d-ecran-2026-07-09-172251.png", reference: "Champignon" },
    { prompt: "Résous ce Rébus !", image: "https://i.postimg.cc/MX89hh1R/Capture-d-ecran-2026-07-09-172323.png", reference: "Monnaie" },
  ],

  /* ================= HISTOIRE ================= */
  histoire: [
    { prompt: "En quelle année a eu lieu la prise de la Bastille ?", reference: "1789" },
    { prompt: "Quel empereur romain a légalisé le christianisme ?", reference: "Constantin" },
    { prompt: "Qui était le premier empereur des Français ?", reference: "Napoléon Bonaparte" },
    { prompt: "En quelle année a débuté la Première Guerre mondiale ?", reference: "1914" },
    { prompt: "Quel traité a mis fin à la Première Guerre mondiale ?", reference: "Le traité de Versailles" },
    { prompt: "Quelle civilisation a construit les pyramides de Gizeh ?", reference: "Les Égyptiens" },
    { prompt: "Qui a lancé l'appel du 18 juin 1940 ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année le mur de Berlin est-il tombé ?", reference: "1989" },
    { prompt: "Quel roi de France est surnommé le « Roi Soleil » ?", reference: "Louis XIV" },
    { prompt: "Quelle bataille marque la défaite finale de Napoléon en 1815 ?", reference: "Waterloo" },
    { prompt: "Qui a dirigé l'URSS pendant la majeure partie de la Seconde Guerre mondiale ?", reference: "Staline" },
    { prompt: "Quelle bataille de 1916 est un symbole de l'enfer des tranchées ?", reference: "Verdun" },
    { prompt: "Quel événement déclenche directement la Première Guerre mondiale ?", reference: "L'assassinat de l'archiduc François-Ferdinand" },
    { prompt: "En quelle année Hitler prend-il le pouvoir en Allemagne ?", reference: "1933" },
    { prompt: "Quelle opération du 6 juin 1944 marque le début de la libération de la France ?", reference: "Le débarquement de Normandie (Overlord)" },
    { prompt: "Qui était le chef de l'État français de Vichy ?", reference: "Philippe Pétain" },
    { prompt: "En quelle année la Seconde Guerre mondiale se termine-t-elle ?", reference: "1945" },
    { prompt: "Quel roi de France a été guillotiné en 1793 ?", reference: "Louis XVI" },
    { prompt: "Quelle est la date symbolique du début de la Révolution française ?", reference: "14 juillet 1789" },
    { prompt: "Quel pays envahit la Pologne en septembre 1939 ?", reference: "L'Allemagne nazie" },
    { prompt: "Quel accord de 1938 cède les Sudètes à Hitler ?", reference: "Les accords de Munich" },
    { prompt: "Quelle organisation est créée en 1945 pour maintenir la paix mondiale ?", reference: "L'ONU" },
    { prompt: "Quel événement de 1917 fait sortir la Russie de la guerre ?", reference: "La révolution russe" },
    { prompt: "Qui a été le premier président de la Ve République ?", reference: "Charles de Gaulle" },
    { prompt: "En quelle année Christophe Colomb atteint-il l'Amérique ?", reference: "1492" },
    { prompt: "Quel empire romain tombe en 476 ?", reference: "L'Empire romain d'Occident" },
    { prompt: "Quelle reine d'Égypte est célèbre pour sa liaison avec César puis Marc Antoine ?", reference: "Cléopâtre" },
    { prompt: "Quel mur sépare Berlin-Est et Berlin-Ouest de 1961 à 1989 ?", reference: "Le mur de Berlin" },
    { prompt: "Quelle guerre oppose le Nord et le Sud des États-Unis (1861-1865) ?", reference: "La guerre de Sécession" },
    { prompt: "Quel navire britannique coule en 1912 après avoir heurté un iceberg ?", reference: "Le Titanic" },
    { prompt: "Quel pharaon égyptien est célèbre pour son masque funéraire en or ?", reference: "Toutankhamon" },
    { prompt: "Quelle bataille de 1815 se déroule en Belgique actuelle ?", reference: "Waterloo" },
    { prompt: "Quel roi anglais signe la Magna Carta en 1215 ?", reference: "Jean sans Terre" },
    { prompt: "Quelle épidémie décime l'Europe au XIVe siècle ?", reference: "La peste noire" },
    { prompt: "Quel explorateur portugais réalise le premier tour du monde (expédition achevée après sa mort) ?", reference: "Magellan" },
    { prompt: "En quelle année la France abolit-elle l'esclavage pour la seconde fois (définitivement) ?", reference: "1848" },
    { prompt: "Quel événement déclenche la Terreur en France en 1793 ?", reference: "L'exécution du roi et la guerre contre les monarchies européennes" },
    { prompt: "Quel traité de 1648 met fin à la guerre de Trente Ans ?", reference: "La paix de Westphalie" },
    { prompt: "Quelle civilisation antique a inventé la démocratie ?", reference: "Les Grecs (Athènes)" },
    { prompt: "Quel dirigeant chinois fonde la République populaire de Chine en 1949 ?", reference: "Mao Zedong" },
    // AJOUTS ICI
    { prompt: "Quelle est la plus ancienne civilisation de la Mésopotamie ?", reference: "Les Sumériens" },
    { prompt: "Qui a découvert le vaccin contre la rage ?", reference: "Louis Pasteur" },
    { prompt: "En quelle année l'Algérie a-t-elle obtenu son indépendance ?", reference: "1962" },
    { prompt: "Quel président américain a aboli l'esclavage ?", reference: "Abraham Lincoln" },
    { prompt: "Quelle guerre a opposé la France et l'Angleterre de 1337 à 1453 ?", reference: "La guerre de Cent Ans" },
    { prompt: "Qui a unifié la Chine pour la première fois ?", reference: "Qin Shi Huang" },
    { prompt: "En quelle année a eu lieu le massacre de la Saint-Barthélemy ?", reference: "1572" },
    { prompt: "Quel roi de France a été surnommé « Le Juste » ?", reference: "Louis XIII" },
    { prompt: "Quelle bataille navale a opposé la flotte franco-espagnole à la flotte britannique en 1805 ?", reference: "La bataille de Trafalgar" },
    { prompt: "Qui était le dernier tsar de Russie ?", reference: "Nicolas II" },
    { prompt: "En quelle année a été signée la Déclaration des droits de l'homme et du citoyen ?", reference: "1789" },
    { prompt: "Quel pays a été divisé par le 38e parallèle après la Seconde Guerre mondiale ?", reference: "La Corée" },
    { prompt: "Qui a été le premier président de la République française (1848) ?", reference: "Louis-Napoléon Bonaparte (Napoléon III)" },
    { prompt: "Quelle cité a été détruite par l'éruption du Vésuve en 79 apr. J.-C. ?", reference: "Pompéi" },
    { prompt: "Quel empereur byzantin a fait construire la basilique Sainte-Sophie ?", reference: "Justinien" },
    { prompt: "Quelle reine d'Angleterre a régné pendant 63 ans, de 1837 à 1901 ?", reference: "La reine Victoria" },
    { prompt: "Quel révolutionnaire cubain a renversé Batista en 1959 ?", reference: "Fidel Castro" },
    { prompt: "En quelle année la loi de séparation des Églises et de l'État a-t-elle été adoptée en France ?", reference: "1905" },
    { prompt: "Quel célèbre conquérant a fondé le plus vaste empire continu de l'histoire, l'Empire mongol ?", reference: "Gengis Khan" },
    { prompt: "Qui a écrit le Manifeste du Parti communiste avec Friedrich Engels ?", reference: "Karl Marx" },
    { prompt: "Quel traité a officiellement créé l'Union européenne en 1992 ?", reference: "Le traité de Maastricht" },
    { prompt: "Quel navigateur portugais fut le premier à atteindre l'Inde par la voie maritime ?", reference: "Vasco de Gama" },
    { prompt: "Sous quelle République la France vit-elle actuellement ?", reference: "La Ve République" },
    { prompt: "Quelle célèbre figure de la Révolution française a été assassinée dans sa baignoire par Charlotte Corday ?", reference: "Jean-Paul Marat" },
    { prompt: "En quelle année Neil Armstrong a-t-il marché sur la Lune ?", reference: "1969" },
  ],

  /* ================= GRANDES FIGURES & ÉVÉNEMENTS ================= */
  grandes_figures: [
    { prompt: "Je suis un général corse devenu empereur des Français. Qui suis-je ?", reference: "Napoléon Bonaparte" },
    { prompt: "Je suis une jeune paysanne qui a mené l'armée française à Orléans avant d'être brûlée vive. Qui suis-je ?", reference: "Jeanne d'Arc" },
    { prompt: "Je suis un physicien qui a formulé la théorie de la relativité. Qui suis-je ?", reference: "Albert Einstein" },
    { prompt: "Je suis un pasteur américain qui a prononcé le discours « I have a dream ». Qui suis-je ?", reference: "Martin Luther King" },
    { prompt: "Je suis une reine d'Égypte, dernière souveraine de la dynastie ptolémaïque. Qui suis-je ?", reference: "Cléopâtre" },
    { prompt: "Je suis un général qui a lancé l'appel du 18 juin 1940 depuis Londres. Qui suis-je ?", reference: "Charles de Gaulle" },
    { prompt: "Je suis un chef d'État sud-africain emprisonné 27 ans avant de devenir président. Qui suis-je ?", reference: "Nelson Mandela" },
    { prompt: "Je suis une scientifique polonaise, seule personne à avoir reçu deux prix Nobel dans deux domaines différents. Qui suis-je ?", reference: "Marie Curie" },
    { prompt: "Je suis un roi de France qui a régné plus de 70 ans, le plus long règne de l'histoire de France. Qui suis-je ?", reference: "Louis XIV" },
    { prompt: "Je suis un dictateur allemand responsable de la Seconde Guerre mondiale et de la Shoah. Qui suis-je ?", reference: "Adolf Hitler" },
    { prompt: "Je suis un premier ministre britannique qui a résisté aux nazis pendant la bataille d'Angleterre. Qui suis-je ?", reference: "Winston Churchill" },
    { prompt: "Je suis un empereur romain qui a légalisé le christianisme. Qui suis-je ?", reference: "Constantin" },
    { prompt: "Je suis un navigateur qui a atteint l'Amérique en 1492 en cherchant une route vers les Indes. Qui suis-je ?", reference: "Christophe Colomb" },
    { prompt: "Je suis une résistante et ministre française, rescapée des camps, dont le visage est sur les manuels d'histoire. Qui suis-je ?", reference: "Simone Veil" },
    { prompt: "Je suis un philosophe grec, maître de Platon devenu maître d'Aristote lui-même. Qui suis-je ?", reference: "Socrate" },
    { prompt: "Je suis un empereur français vaincu définitivement à Waterloo en 1815. Qui suis-je ?", reference: "Napoléon Bonaparte" },
    { prompt: "Je suis un leader indien qui a mené la résistance non-violente contre la colonisation britannique. Qui suis-je ?", reference: "Gandhi" },
    { prompt: "Je suis un tsar russe qui a modernisé la Russie et fondé Saint-Pétersbourg. Qui suis-je ?", reference: "Pierre le Grand" },
    { prompt: "Je suis une figure de la Résistance française, chargé par de Gaulle d'unifier les mouvements clandestins. Qui suis-je ?", reference: "Jean Moulin" },
    { prompt: "Je suis un roi macédonien qui a conquis un immense empire jusqu'en Inde avant 33 ans. Qui suis-je ?", reference: "Alexandre le Grand" },
    { prompt: "Je suis un président américain assassiné à Dallas en 1963. Qui suis-je ?", reference: "John F. Kennedy" },
    { prompt: "Je suis un empereur romain connu pour avoir conquis la Gaule. Qui suis-je ?", reference: "Jules César" },
    { prompt: "Je suis un inventeur américain à qui l'on attribue l'ampoule électrique. Qui suis-je ?", reference: "Thomas Edison" },
    { prompt: "Je suis une reine de France, épouse de Louis XVI, guillotinée en 1793. Qui suis-je ?", reference: "Marie-Antoinette" },
    { prompt: "Je suis un peintre néerlandais connu pour m'être coupé l'oreille. Qui suis-je ?", reference: "Vincent van Gogh" },
    { prompt: "Je suis le premier homme à avoir marché sur la Lune, en 1969. Qui suis-je ?", reference: "Neil Armstrong" },
    { prompt: "Je suis un chef militaire carthaginois qui a traversé les Alpes avec des éléphants. Qui suis-je ?", reference: "Hannibal Barca" },
    { prompt: "Je suis un compositeur allemand devenu sourd qui a continué à composer. Qui suis-je ?", reference: "Ludwig van Beethoven" },
    { prompt: "Je suis un moine allemand à l'origine de la Réforme protestante. Qui suis-je ?", reference: "Martin Luther" },
    { prompt: "Je suis un pharaon dont la tombe intacte a été découverte en 1922 par Howard Carter. Qui suis-je ?", reference: "Toutankhamon" },
    { prompt: "Je suis une aviatrice américaine disparue en 1937 en tentant de faire le tour du monde. Qui suis-je ?", reference: "Amelia Earhart" },
    { prompt: "Je suis un écrivain et aviateur français, auteur du « Petit Prince », disparu en vol en 1944. Qui suis-je ?", reference: "Antoine de Saint-Exupéry" },
    { prompt: "Je suis un chef d'État soviétique à l'origine de la Révolution d'Octobre 1917. Qui suis-je ?", reference: "Lénine" },
    { prompt: "Je suis un savant italien condamné par l'Église pour avoir défendu que la Terre tourne autour du Soleil. Qui suis-je ?", reference: "Galilée" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/T107mtZS/AC.png", reference: "Acacio" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/ygpyGbKL/boschman.png", reference: "Boschman" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/vx1twt8h/dada.png", reference: "Adem" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/y3JyCy6h/deloeil.jpg", reference: "Tyméo/Deloeil" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/xNk3V3jv/Maxime.png", reference: "Tiropijon" },
    { prompt: "Qui est cette figure reconnu chez Acacio's Family ?", image: "https://i.postimg.cc/MfcmJmZs/Simon.png", reference: "Simon" },
    // AJOUTS ICI
    { prompt: "Je suis un grand peintre et inventeur de la Renaissance, auteur de La Joconde. Qui suis-je ?", reference: "Léonard de Vinci" },
    { prompt: "Je suis l'auteur du célèbre roman français Les Misérables. Qui suis-je ?", reference: "Victor Hugo" },
    { prompt: "Je suis une militante noire américaine célèbre pour avoir refusé de céder ma place dans un bus en 1955. Qui suis-je ?", reference: "Rosa Parks" },
    { prompt: "Je suis un scientifique britannique qui a formulé la théorie de l'évolution des espèces. Qui suis-je ?", reference: "Charles Darwin" },
    { prompt: "Je suis un boxeur légendaire américain, initialement nommé Cassius Clay, surnommé « The Greatest ». Qui suis-je ?", reference: "Muhammad Ali" },
    { prompt: "Je suis une reine d'Écosse exécutée sur ordre de ma cousine Élisabeth Ire. Qui suis-je ?", reference: "Marie Stuart" },
    { prompt: "Je suis le plus célèbre auteur dramatique français, créateur de L'Avare et du Tartuffe. Qui suis-je ?", reference: "Molière" },
    { prompt: "Je suis l'actuelle princesse de Galles et future reine consort du Royaume-Uni. Qui suis-je ?", reference: "Kate Middleton" },
    { prompt: "Je suis une figure centrale de la Révolution française, instigateur de la Terreur, surnommé « L'Incorruptible ». Qui suis-je ?", reference: "Maximilien de Robespierre" },
    { prompt: "Je suis un mathématicien britannique considéré comme le père de l'informatique, célèbre pour avoir déchiffré la machine Enigma. Qui suis-je ?", reference: "Alan Turing" },
    { prompt: "Je suis une cosmonaute soviétique, la première femme à avoir effectué un vol dans l'espace en 1963. Qui suis-je ?", reference: "Valentina Terechkova" },
    { prompt: "Je suis une militante pakistanaise pour l'éducation des filles, devenue la plus jeune lauréate du prix Nobel de la paix. Qui suis-je ?", reference: "Malala Yousafzai" },
    { prompt: "Je suis l'homme d'affaires américain cofondateur de la marque Apple. Qui suis-je ?", reference: "Steve Jobs" },
    { prompt: "Je suis un physicien britannique connu pour mes travaux sur les trous noirs et mon best-seller « Une brève histoire du temps ». Qui suis-je ?", reference: "Stephen Hawking" },
    { prompt: "Je suis une artiste peintre mexicaine reconnue pour mes autoportraits intenses et colorés. Qui suis-je ?", reference: "Frida Kahlo" },
    { prompt: "Je suis le compositeur autrichien prodige auteur de La Flûte enchantée. Qui suis-je ?", reference: "Wolfgang Amadeus Mozart" },
    { prompt: "Je suis un industriel américain qui a popularisé le travail à la chaîne avec mon modèle T. Qui suis-je ?", reference: "Henry Ford" },
    { prompt: "Je suis un célèbre trompettiste de jazz, surnommé Satchmo. Qui suis-je ?", reference: "Louis Armstrong" },
    { prompt: "Je suis l'ingénieur français qui a construit la grande tour métallique de Paris pour l'Exposition universelle de 1889. Qui suis-je ?", reference: "Gustave Eiffel" },
    { prompt: "Je suis le chef spirituel tibétain exilé, récompensé par le prix Nobel de la paix en 1989. Qui suis-je ?", reference: "Le Dalaï-Lama" },
    { prompt: "Je suis le pionnier américain de l'animation, créateur du personnage de Mickey Mouse. Qui suis-je ?", reference: "Walt Disney" },
    { prompt: "Je suis l'écrivaine britannique mondialement connue pour avoir créé la saga littéraire Harry Potter. Qui suis-je ?", reference: "J.K. Rowling" },
    { prompt: "Je suis le leader sud-africain de la lutte contre l'apartheid et devenu le premier président noir du pays. Qui suis-je ?", reference: "Nelson Mandela" },
    { prompt: "Je suis une sainte catholique albanaise qui a consacré sa vie aux pauvres dans les bidonvilles de Calcutta. Qui suis-je ?", reference: "Mère Teresa" },
    { prompt: "Je suis l'astronaute français, devenu très populaire, ayant séjourné deux fois dans la Station spatiale internationale. Qui suis-je ?", reference: "Thomas Pesquet" },
  ],

  /* ================= FRANÇAIS ================= */
  francais: [
    { prompt: "Quel est le féminin de « loup » ?", reference: "Louve" },
    { prompt: "Conjuguez « aller » à la 1ère personne du singulier au futur simple.", reference: "J'irai" },
    { prompt: "Quel est le pluriel de « cheval » ?", reference: "Chevaux" },
    { prompt: "Comment appelle-t-on une figure de style qui compare deux éléments avec « comme » ?", reference: "Une comparaison" },
    { prompt: "Quel est l'antonyme de « heureux » ?", reference: "Malheureux (ou triste)" },
    { prompt: "Combien de « p » y a-t-il dans le mot « appartement » ?", reference: "Deux" },
    { prompt: "Quel est le participe passé du verbe « prendre » ?", reference: "Pris" },
    { prompt: "Comment appelle-t-on une phrase qui pose une question ?", reference: "Une phrase interrogative" },
    { prompt: "Quel est le contraire de « monter » ?", reference: "Descendre" },
    { prompt: "« Cet homme est plus grand que moi » : quel est le mot qui exprime la comparaison ?", reference: "Plus... que" },
    { prompt: "Quel est le féminin de « acteur » ?", reference: "Actrice" },
    { prompt: "Comment écrit-on correctement : « malgré que » ou « bien que » est correct grammaticalement ?", reference: "Bien que" },
    { prompt: "Quel est l'homophone de « ver » qui désigne la couleur ?", reference: "Vert" },
    { prompt: "Quel temps exprime une action habituelle dans le passé : « Il jouait tous les jours » ?", reference: "L'imparfait" },
    { prompt: "Quel est le synonyme de « rapide » ?", reference: "Vite (ou véloce)" },
    { prompt: "Comment appelle-t-on un mot qui a le même sens qu'un autre ?", reference: "Un synonyme" },
    { prompt: "Quel est le pluriel de « journal » ?", reference: "Journaux" },
    { prompt: "« Je mange » à quelle personne et quel temps ?", reference: "1ère personne du singulier, présent" },
    { prompt: "Quel est l'antonyme de « facile » ?", reference: "Difficile" },
    { prompt: "Comment appelle-t-on la répétition d'un son en début de mots proches (« Pour qui sont ces serpents qui sifflent... ») ?", reference: "Une allitération" },
    { prompt: "Quel est le féminin de « directeur » ?", reference: "Directrice" },
    { prompt: "Quel mot invariable relie deux propositions : « et », « ou », « mais »... comment appelle-t-on ça ?", reference: "Une conjonction de coordination" },
    { prompt: "Quel est le participe présent du verbe « chanter » ?", reference: "Chantant" },
    { prompt: "Comment écrit-on le son [s] dans « garçon » ?", reference: "Avec une cédille (ç)" },
    { prompt: "Quel est l'antonyme de « acheter » ?", reference: "Vendre" },
    { prompt: "Quel est le pluriel de « œil » ?", reference: "Yeux" },
    { prompt: "Quel mode utilise-t-on pour donner un ordre : « Sors ! » ?", reference: "L'impératif" },
    { prompt: "Quel est le féminin de « roi » ?", reference: "Reine" },
    { prompt: "Comment appelle-t-on une phrase exclamative typique : « Quelle belle journée ! » ?", reference: "Une phrase exclamative" },
    { prompt: "Quel est le synonyme de « content » ?", reference: "Heureux (ou joyeux)" },
    { prompt: "« Ils se sont lavés » : pourquoi le participe passé s'accorde-t-il ici ?", reference: "Verbe pronominal, l'action est réfléchie sur le sujet (COD placé avant)" },
    { prompt: "Quel est le contraire de « commencer » ?", reference: "Finir (ou terminer)" },
    { prompt: "Quel est le pluriel de « bijou » ?", reference: "Bijoux" },
    { prompt: "Comment appelle-t-on un texte qui raconte une histoire à la 1ère personne, souvent autobiographique ?", reference: "Un récit à la première personne (ou autobiographie)" },
    { prompt: "Quel est l'homophone de « sont » qui indique la possession ?", reference: "Son" },
    { prompt: "Quel est le féminin de « époux » ?", reference: "Épouse" },
    { prompt: "Quel temps utilise-t-on pour une action qui vient de se terminer et a un lien avec le présent : « J'ai mangé » ?", reference: "Le passé composé" },
    { prompt: "Quel est le pluriel de « travail » ?", reference: "Travaux" },
    { prompt: "Comment appelle-t-on une exagération volontaire (« Je meurs de faim ») ?", reference: "Une hyperbole" },
    { prompt: "Quel est l'antonyme de « ouvrir » ?", reference: "Fermer" },
    // AJOUTS ICI
    { prompt: "Donnez un synonyme courant du mot « Vacarme ».", reference: "Bruit, chahut, tapage" },
    { prompt: "Comment s'appelle le temps du passé exprimant une action qui s'est déroulée avant une autre action passée ?", reference: "Le plus-que-parfait" },
    { prompt: "Quel est le féminin de « jumeau » ?", reference: "Jumelle" },
    { prompt: "Complétez le célèbre proverbe : « Pierre qui roule n'amasse pas... »", reference: "Mousse" },
    { prompt: "Quel est le pluriel du mot « chacal » ?", reference: "Chacals (avec un S, c'est une exception)" },
    { prompt: "Comment appelle-t-on un mot dont la prononciation imite le bruit de la chose qu'il désigne (ex : tic-tac, boum) ?", reference: "Une onomatopée" },
    { prompt: "Quel est l'infinitif du verbe conjugué dans la phrase : « Nous fûmes ravis » ?", reference: "Être (au passé simple)" },
    { prompt: "Quelle figure de style consiste à attribuer des caractéristiques humaines à un objet ou un animal ?", reference: "La personnification" },
    { prompt: "Quel est l'antonyme de « éphémère » ?", reference: "Durable, éternel, pérenne" },
    { prompt: "Comment écrit-on le mot composé « chef-d'œuvre » au pluriel ?", reference: "Chefs-d'œuvre" },
    { prompt: "Quelle est la fonction grammaticale du mot « rouge » dans l'expression « La voiture rouge » ?", reference: "Épithète (liée au nom voiture)" },
    { prompt: "Conjuguez le verbe « avoir » à l'imparfait du subjonctif, à la 1ère personne du singulier.", reference: "Que j'eusse" },
    { prompt: "Quel est le participe passé du verbe « mourir » ?", reference: "Mort" },
    { prompt: "Quelle figure de style rapproche deux mots de sens contraire au sein d'une même expression (ex: un silence assourdissant) ?", reference: "Un oxymore" },
    { prompt: "Quel est le pluriel du mot « vitrail » ?", reference: "Vitraux" },
    { prompt: "Comment appelle-t-on un mot ou un groupe de mots qui peut se lire de gauche à droite ou de droite à gauche avec le même sens (ex: kayak, radar) ?", reference: "Un palindrome" },
    { prompt: "Quel est l'antonyme (moment de la journée) de « crépuscule » ?", reference: "Aube, aurore" },
    { prompt: "Complétez cette expression française signifiant avoir un défaut de prononciation : « Avoir un cheveu sur la... »", reference: "Langue" },
    { prompt: "Quel est le féminin de l'adjectif « vieux » ?", reference: "Vieille" },
    { prompt: "Quels pronoms personnels sont utilisés pour remplacer un COD inanimé (ou animé) défini ?", reference: "Le, la, les, l'" },
    { prompt: "Quel mode verbal est traditionnellement utilisé en français pour exprimer le doute, la volonté ou le souhait ?", reference: "Le subjonctif" },
    { prompt: "Quel est le synonyme soutenu de « généreux » signifiant qu'on aime donner sans compter ?", reference: "Altruiste, prodigue, charitable" },
    { prompt: "Dans la phrase « Il y a deux cents personnes », comment écrit-on cent au pluriel ?", reference: "Cents (avec un S, car il est multiplié et termine le nombre)" },
    { prompt: "Quelle est la nature du mot « lentement » ?", reference: "Un adverbe" },
    { prompt: "Comment s'appelle la branche de la linguistique qui étudie les sons de la langue ?", reference: "La phonétique" },
  ],

  /* ================= MARQUES & ENTREPRISES (par indices) ================= */
  marques: [
    { prompt: "Quel est cette marque ?", image: "https://lb-prod.fr/cdn/shop/articles/Capture_d_ecran_2023-03-07_155504.png?v=1678200918", reference: "Adidas" },
    { prompt: "Quel est cette marque ?", image: "https://www.pixartprinting.it/blog/wp-content/uploads/2023/12/1995-1024x561.jpg", reference: "Nike" },
    { prompt: "Quel est cette marque ?", image: "https://assets.renaultgroup.com/uploads/2021/03/nouveau_logo_renault.jpg?format=webp&width=3840", reference: "Renault" },
    { prompt: "Quel est cette marque ?", image: "https://uploads.audi.com/system/production/media/116125/images/74022a65b478f7b3a8e0bf8ba70994f66fde5dd7/A231415_web_2880.jpg?1698528985", reference: "Audi" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTb4lvXVxmncUmXkmc_lMQRh4s3AqtMHxtlkYHU2wAqA&s=10", reference: "Apple" },
    { prompt: "Quel est cette marque ?", image: "https://guide-images.cdn.ifixit.com/igi/TANXpRsbOhvSlC5A.medium", reference: "Samsung" },
    { prompt: "Quel est cette marque ?", image: "https://www.danstapub.com/wp-content/uploads/2015/07/dans-ta-pub-coca-cola-the-first-ever-no-labels-media-promo-design-pr-3.jpg", reference: "Coca-Cola" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/e/ea/Mcdonalds_France_2009_logo.svg/3840px-Mcdonalds_France_2009_logo.svg.png", reference: "McDonald's" },
    { prompt: "Quel est cette marque ?", image: "https://static.vecteezy.com/ti/vecteur-libre/p1/21608791-louis-vuitton-logo-louis-vuitton-icone-sur-marron-contexte-gratuit-vectoriel.jpg", reference: "Louis Vuitton" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2020/04/Lacoste-Embl%C3%A8me.jpg", reference: "Lacoste" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png", reference: "Instagram" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_%22G%22_logo.svg/3840px-Google_%22G%22_logo.svg.png", reference: "Google" },
    { prompt: "Quel est cette marque ?", image: "https://ih1.redbubble.net/image.5585518331.4410/st,small,507x507-pad,600x600,f8f8f8.u2.jpg", reference: "IKEA" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c0/Scuderia_Ferrari_Logo.svg/1920px-Scuderia_Ferrari_Logo.svg.png", reference: "Ferrari" },
    { prompt: "Quel est cette marque ?", image: "https://img.icons8.com/color/1200/nintendo-switch-logo.jpg", reference: "Nintendo Switch" },
    { prompt: "Quel est cette marque ?", image: "https://static.vecteezy.com/system/resources/thumbnails/019/766/223/small/amazon-logo-amazon-icon-transparent-free-png.png", reference: "Amazon" },
    { prompt: "Quel est cette marque ?", image: "https://img.lemde.fr/2017/06/22/7/0/276/137/1342/671/60/0/8e068ea_28878-y9u3wo.vt083680k9.PNG", reference: "Danone" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2022/05/Toyota-logo.png", reference: "Toyota" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Monogramme_Nespresso.png/250px-Monogramme_Nespresso.png", reference: "Nespresso" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2025/04/X-Logo.jpg", reference: "Twitter (X)" },
    { prompt: "Quel est cette marque ?", image: "https://cdn-icons-png.flaticon.com/512/5968/5968613.png", reference: "L'Oréal" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTONbMWa0xoap84mP0TcfclTnxmsjDnmjEkRkauTVYYSA&s=10", reference: "Starbucks" },
    { prompt: "Quel est cette marque ?", image: "https://assets.turbologo.com/blog/fr/2019/11/19134135/puma-logo-cover.png", reference: "Puma" },
    { prompt: "Quel est cette marque ?", image: "https://www.decoracing.com/366-large_default/bmw-sticker-logo-classique-bmw-m.jpg", reference: "BMW" },
    { prompt: "Quel est cette marque ?", image: "https://decoglam.net/storage/images/image?remote=https%3A%2F%2Fdecoglam.net%2FWebRoot%2FStore20%2FShops%2F57b2465e-10e3-4ede-a8d1-6ede59d24921%2F6161%2F52F8%2F7F2C%2F2C42%2F6FC0%2F0A48%2F356B%2FBFA3%2Fhermes-paris.jpg&shop=57b2465e-10e3-4ede-a8d1-6ede59d24921", reference: "Hermès" },
    { prompt: "Quel est cette marque ?", image: "https://www.numerama.com/content/uploads/2016/06/13502130_10153696123838870_522765110773053650_n-796x796-2.png", reference: "Netflix" },
    { prompt: "Quel est cette marque ?", image: "https://cdn.worldvectorlogo.com/logos/michelin-2.svg", reference: "Michelin" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/3840px-Microsoft_logo.svg.png", reference: "Microsoft (pas Domino's pizza)" },
    { prompt: "Quel est cette marque ?", image: "https://embroideres.com/files/cache/042a7c76b4c950dc1882acfc97f5cf25_f1000671.jpg", reference: "KFC" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2021/02/Logo-Tesla.jpg", reference: "Tesla" },
    { prompt: "Quel est cette marque ?", image: "https://logos-marques.com/wp-content/uploads/2020/04/Chanel-Symbole.jpg", reference: "Chanel" },
    { prompt: "Quel est cette marque ?", image: "https://assets.turbologo.com/blog/en/2021/07/07075142/PlayStation-logo-1994.png", reference: "Playstation" },
    { prompt: "Quel est cette marque ?", image: "https://www.art-deco-stickers.fr/16913/sticker-autocollant-logo-embleme-yamaha.jpg", reference: "Yamaha" },
    { prompt: "A quel entreprise appartient ce logo ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3XBDKzvzGd7H0d9OhJwi5tBiZhUybpbT3xWcfhgzy4w&s=10", reference: "Warner Bros" },
    { prompt: "Quel est cette marque ?", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e8/Shell_logo.svg/3840px-Shell_logo.svg.png", reference: "Shell" },
    { prompt: "Quel est cette marque ?", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIBhgjk1R4SaJKM1qdv7SHJTwW5i1uK8OfOvhjkyfdX8cCWRd3oYeku_jW&s=10", reference: "WWF" },
    { prompt: "Quel est cette marque ?", image: "https://play-lh.googleusercontent.com/-sfpej5glWUgJjbt7kPKC3ChTyWIeKPGPA7CyrqYlCZWd16sxCYlZBU1x1ohmMd_IVQwk3CCfByOSw1EnFRc=w600-h300-pc0xffffff-pd", reference: "Crousty one" },
  ],

  /* ================= CULTURE GÉNÉRALE ================= */
  culture_generale: [
    { prompt: "Combien de continents compte-t-on généralement ?", reference: "5" },
    { prompt: "Quelle est la monnaie utilisée au Japon ?", reference: "Le yen" },
    { prompt: "Quel est le plus grand océan du monde ?", reference: "L'océan Pacifique" },
    { prompt: "Combien de couleurs compte l'arc-en-ciel traditionnellement ?", reference: "7" },
    { prompt: "Quelle est la langue la plus parlée au monde (à échelles de locuteurs natifs) ?", reference: "Le mandarin" },
    { prompt: "Quel est le symbole chimique de l'eau ?", reference: "H2O" },
    { prompt: "Combien de jours compte une année bissextile ?", reference: "366" },
    { prompt: "Quel pays a la forme d'une botte sur la carte d'Europe ?", reference: "L'Italie" },
    { prompt: "Quel est l'instrument de musique à 88 touches ?", reference: "Le piano" },
    { prompt: "Quelle planète est surnommée la « planète rouge » ?", reference: "Mars" },
    { prompt: "Combien de temps la Lune met-elle environ à tourner autour de la Terre ?", reference: "Environ 27 à 29 jours" },
    { prompt: "Quel est le plus long fleuve de France ?", reference: "La Loire" },
    { prompt: "Quel sport se joue à Wimbledon ?", reference: "Le tennis" },
    { prompt: "Combien de cordes compte une guitare classique ?", reference: "6" },
    { prompt: "Quelle est la capitale de l'Italie ?", reference: "Rome" },
    { prompt: "Quel est l'animal terrestre le plus rapide du monde ?", reference: "Le guépard" },
    { prompt: "Combien de faces possède un dé classique ?", reference: "6" },
    { prompt: "Quel gaz respirons-nous principalement pour vivre ?", reference: "L'oxygène" },
    { prompt: "Quelle est la capitale de l'Espagne ?", reference: "Madrid" },
    { prompt: "Combien de temps dure une olympiade ?", reference: "4 ans" },
    { prompt: "Quel est le plus petit os du corps humain ?", reference: "L'étrier (dans l'oreille)" },
    { prompt: "Quelle est la capitale du Japon ?", reference: "Tokyo" },
    { prompt: "Quel fruit est associé à Isaac Newton et la découverte de la gravité ?", reference: "La pomme" },
    { prompt: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", reference: "Environ 8 minutes" },
    { prompt: "Quelle est la capitale de l'Allemagne ?", reference: "Berlin" },
    { prompt: "Quel est le nom du satellite naturel de la Terre ?", reference: "La Lune" },
    { prompt: "Combien de pattes a une araignée ?", reference: "8" },
    { prompt: "Quelle est la plus grande île du monde ?", reference: "Le Groenland" },
    { prompt: "Quel métal est symbolisé par « Au » ?", reference: "L'or" },
    { prompt: "Quel pays a inventé le sushi ?", reference: "Le Japon" },
    { prompt: "Quelle est la vitesse du son approximativement dans l'air ?", reference: "Environ 340 mètres par seconde" },
    { prompt: "Quel organe humain filtre le sang pour produire l'urine ?", reference: "Le rein" },
    { prompt: "Quelle est la capitale du Portugal ?", reference: "Lisbonne" },
    { prompt: "Combien de dents a un adulte en moyenne ?", reference: "32" },
    { prompt: "Quel est le plus grand désert froid du monde ?", reference: "L'Antarctique" },
    { prompt: "Quelle est la monnaie utilisée au Royaume-Uni ?", reference: "La livre sterling" },
    { prompt: "Quel est l'organe principal du système nerveux ?", reference: "Le cerveau" },
    { prompt: "Combien de zéros comporte un million écrit en chiffres ?", reference: "6" },
    { prompt: "Quelle est la capitale de la Russie ?", reference: "Moscou" },
    { prompt: "Quel animal est le meilleur ami de l'homme, selon l'expression ?", reference: "Le chien" },
    { prompt: "Quel est le plus haut sommet d'Europe ?", reference: "Le mont Elbrouz (ou le Mont Blanc pour l'Europe de l'Ouest)" },
    { prompt: "Combien de continents la Russie chevauche-t-elle ?", reference: "2 (Europe et Asie)" },
    { prompt: "Quel est le plus grand pays d'Afrique par la population ?", reference: "Le Nigeria" },
    { prompt: "Quelle est la capitale des États-Unis ?", reference: "Washington D.C." },
    { prompt: "Quel est le symbole chimique du sel de table ?", reference: "NaCl" },
    { prompt: "Quelle est la couleur obtenue en mélangeant le bleu et le jaune ?", reference: "Le vert" },
    { prompt: "Quel est le plus grand mammifère marin ?", reference: "La baleine bleue" },
    { prompt: "Combien de minutes dure un match de basketball NBA hors prolongations ?", reference: "48 minutes" },
    { prompt: "Quel est le nom de la galaxie qui contient notre système solaire ?", reference: "La Voie lactée" },
    { prompt: "Quelle est la capitale de la Chine ?", reference: "Pékin" },
    // AJOUTS ICI
    { prompt: "Quel est le plus petit pays du monde ?", reference: "Le Vatican" },
    { prompt: "Dans quel pays se trouve le célèbre site inca du Machu Picchu ?", reference: "Le Pérou" },
    { prompt: "Quelle est la véritable capitale de l'Australie (et non Sydney) ?", reference: "Canberra" },
    { prompt: "Quel est le sommet le plus haut du monde par rapport au niveau de la mer ?", reference: "L'Everest" },
    { prompt: "Quel célèbre peintre espagnol a réalisé la toile « Guernica » ?", reference: "Pablo Picasso" },
    { prompt: "Quel est le sport le plus pratiqué et regardé au monde ?", reference: "Le football" },
    { prompt: "Quel fruit est l'ingrédient principal de la recette du guacamole mexicain ?", reference: "L'avocat" },
    { prompt: "Quelle est la monnaie officielle de la Suisse ?", reference: "Le franc suisse" },
    { prompt: "Quelle mer s'étend entre la Grèce à l'ouest et la Turquie à l'est ?", reference: "La mer Égée" },
    { prompt: "Quelle est la plus grande planète de notre système solaire ?", reference: "Jupiter" },
    { prompt: "Quel animal marsupial est un grand symbole de l'Australie, en plus du kangourou ?", reference: "Le koala (ou l'émeu)" },
    { prompt: "Quelle célèbre ville américaine est mondialement surnommée « La Grosse Pomme » (The Big Apple) ?", reference: "New York" },
    { prompt: "Quel élément chimique essentiel à la vie porte le symbole O ?", reference: "L'oxygène" },
    { prompt: "Quelle saga cinématographique met en scène le sorcier surnommé « L'Élu » portant une cicatrice en éclair ?", reference: "Harry Potter" },
    { prompt: "Quel pays a dépassé la Chine pour devenir le plus peuplé du monde ?", reference: "L'Inde" },
    { prompt: "Quel petit fruit rouge est utilisé pour fabriquer la liqueur appelée kirsch ?", reference: "La cerise" },
    { prompt: "Quel océan borde toute la côte Est des États-Unis ?", reference: "L'océan Atlantique" },
    { prompt: "En astronomie, comment appelle-t-on le phénomène d'une étoile massive qui explose ?", reference: "Une supernova" },
    { prompt: "Quel instrument de musique à cordes est indissociable de la danse et musique du flamenco ?", reference: "La guitare (flamenca)" },
    { prompt: "Dans quel célèbre jeu vidéo explore-t-on la région de Bordeciel (Skyrim) sur le continent de Tamriel ?", reference: "The Elder Scrolls (V: Skyrim)" },
    { prompt: "Quelle est la langue officielle du Brésil ?", reference: "Le portugais" },
    { prompt: "De quel pays européen les célèbres briques de construction Lego sont-elles originaires ?", reference: "Le Danemark" },
    { prompt: "Quelle est la capitale du Canada ?", reference: "Ottawa" },
    { prompt: "Quelle est la couleur du légendaire cheval blanc d'Henri IV ?", reference: "Blanc" },
    { prompt: "Quel fleuve d'Amérique du Sud est considéré par la plupart des géographes modernes comme le plus long et le plus puissant du monde ?", reference: "L'Amazone" },
  ],
};

const CATEGORY_LABELS = {
  animaux: "Animaux",
  petit_bac: "Petit Bac",
  rebus: "Rébus",
  histoire: "Histoire",
  grandes_figures: "Grandes figures & événements",
  francais: "Français",
  marques: "Marques (indices)",
  culture_generale: "Culture générale",
};

// Rend la banque accessible en tant que module (utilisée par app.js)
if (typeof module !== 'undefined') { module.exports = QUESTION_BANK; }
if (typeof window !== 'undefined') { window.QUESTION_BANK = QUESTION_BANK; window.CATEGORY_LABELS = CATEGORY_LABELS; }
